# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
# Clear any existing cache before install to avoid EBUSY errors
cmds = ["rm -rf node_modules/.cache || true", "npm ci --legacy-peer-deps"]

[phases.build]
dependsOn = ["install"]
# Clear Next.js cache before build to avoid conflicts
cmds = ["rm -rf .next/cache || true", "npm run build:standalone"]

[start]
cmd = "npm run start:prod"