# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci --legacy-peer-deps"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build:standalone"]

[start]
cmd = "npm run start:prod"