[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/api/health-check"
healthcheckTimeout = 60
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

# Make environment variables available during build
[build.env]
NEXT_PUBLIC_SUPABASE_URL = { variable = "NEXT_PUBLIC_SUPABASE_URL" }
NEXT_PUBLIC_SUPABASE_ANON_KEY = { variable = "NEXT_PUBLIC_SUPABASE_ANON_KEY" }
SUPABASE_SERVICE_ROLE_KEY = { variable = "SUPABASE_SERVICE_ROLE_KEY" }
ANTHROPIC_API_KEY = { variable = "ANTHROPIC_API_KEY" }
