# Railway deployment configuration

[build]
builder = "NIXPACKS"
buildCommand = "npm ci --legacy-peer-deps && npm run build:standalone"

[deploy]
startCommand = "npm run start:prod"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"