// /lib/assessment/essential-questions.ts

export interface EssentialQuestion {
  id: string;
  text: string;
  type:
    | "LIKERT_SCALE"
    | "YES_NO"
    | "MULTIPLE_CHOICE"
    | "FREQUENCY"
    | "TEXT"
    | "MULTI_SELECT"
    | "NUMBER";
  module:
    | "SCREENING"
    | "DIGESTIVE"
    | "IMMUNE"
    | "ENERGY"
    | "HORMONAL"
    | "NEUROLOGICAL"
    | "CARDIOVASCULAR"
    | "DETOX";
  order: number;
  required?: boolean;
  options?: string[];
  scale?: {
    min: number;
    max: number;
    minLabel: string;
    maxLabel: string;
  };
  conditionalLogic?: {
    dependsOn: string; // Question ID this depends on
    showIf: any; // Value that triggers this question or function to evaluate
  };
  placeholder?: string; // Placeholder text for text inputs
}

export const ESSENTIAL_QUESTIONS: EssentialQuestion[] = [
  // ========== SCREENING MODULE (8 questions) ==========
  {
    id: "essential-energy-level",
    module: "SCREENING",
    order: 1,
    text: "Rate your overall energy level throughout the day",
    type: "LIKERT_SCALE",
    required: true,
    scale: { min: 0, max: 5, minLabel: "Exhausted", maxLabel: "Excellent" },
  },
  {
    id: "essential-sleep-quality",
    module: "SCREENING",
    order: 2,
    text: "How would you rate your sleep quality?",
    type: "LIKERT_SCALE",
    required: true,
    scale: { min: 0, max: 5, minLabel: "Terrible", maxLabel: "Excellent" },
  },
  {
    id: "essential-stress-level",
    module: "SCREENING",
    order: 3,
    text: "Rate your current stress level",
    type: "LIKERT_SCALE",
    required: true,
    scale: {
      min: 0,
      max: 5,
      minLabel: "No stress",
      maxLabel: "Extreme stress",
    },
  },
  {
    id: "essential-digestive-issues",
    module: "SCREENING",
    order: 4,
    text: "Do you experience digestive issues after meals?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-digestive-issues-details",
    module: "SCREENING",
    order: 4.1,
    text: "Please select your digestive symptoms",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Bloating",
      "Gas",
      "Stomach pain",
      "Nausea",
      "Heartburn/Acid reflux",
      "Cramping",
      "Diarrhea",
      "Constipation",
      "Feeling too full",
      "Loss of appetite",
      "Burping",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-digestive-issues",
      showIf: "yes",
    },
  },
  {
    id: "essential-digest-severity",
    module: "SCREENING",
    order: 4.2,
    text: "Rate the overall severity of your digestive symptoms",
    type: "LIKERT_SCALE",
    required: false,
    scale: { min: 0, max: 5, minLabel: "None/Mild", maxLabel: "Severe" },
    conditionalLogic: {
      dependsOn: "essential-digestive-issues-details",
      showIf: "hasAnySelection", // Special value to check if any items selected
    },
  },
  {
    id: "essential-digest-triggers",
    module: "SCREENING",
    order: 4.3,
    text: "What typically triggers your digestive symptoms?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Eating any food",
      "Specific foods",
      "Large meals",
      "Eating too quickly",
      "Stress",
      "Travel",
      "Antibiotics",
      "Time of day",
      "No clear pattern",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-digestive-issues-details",
      showIf: "hasAnySelection",
    },
  },
  {
    id: "essential-food-sensitivities",
    module: "SCREENING",
    order: 5,
    text: "Do you have any known food sensitivities or allergies?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-food-list",
    module: "SCREENING",
    order: 5.1,
    text: "Which foods do you react to?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Dairy",
      "Gluten/Wheat",
      "Eggs",
      "Soy",
      "Corn",
      "Peanuts",
      "Tree nuts",
      "Shellfish",
      "Fish",
      "Nightshades (tomatoes, peppers)",
      "Citrus",
      "Chocolate",
      "Coffee",
      "Alcohol",
      "Sugar",
      "Artificial sweeteners",
      "MSG",
      "Sulfites",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-food-sensitivities",
      showIf: "yes",
    },
  },
  {
    id: "essential-chronic-conditions",
    module: "SCREENING",
    order: 6,
    text: "Do you have any diagnosed chronic health conditions?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-chronic-conditions-list",
    module: "SCREENING",
    order: 6.1,
    text: "Which chronic health conditions do you have?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Diabetes (Type 1)",
      "Diabetes (Type 2)",
      "High Blood Pressure",
      "Heart Disease",
      "Thyroid Disorder",
      "Arthritis",
      "Asthma",
      "COPD",
      "Chronic Fatigue Syndrome",
      "Fibromyalgia",
      "Depression",
      "Anxiety Disorder",
      "Cancer",
      "Kidney Disease",
      "Liver Disease",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-chronic-conditions",
      showIf: "yes",
    },
  },
  {
    id: "essential-chronic-impact",
    module: "SCREENING",
    order: 6.2,
    text: "How much do your chronic conditions impact your daily life?",
    type: "LIKERT_SCALE",
    required: false,
    scale: { min: 0, max: 5, minLabel: "No impact", maxLabel: "Severe impact" },
    conditionalLogic: {
      dependsOn: "essential-chronic-conditions-list",
      showIf: "hasAnySelection",
    },
  },
  {
    id: "essential-medications",
    module: "SCREENING",
    order: 7,
    text: "Are you currently taking any medications or supplements?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-medications-list",
    module: "SCREENING",
    order: 7.1,
    text: "List your medications and supplements",
    type: "TEXT",
    required: false,
    placeholder:
      "Example: Metformin 500mg, Vitamin D 2000IU, Fish Oil, Thyroid medication",
    conditionalLogic: {
      dependsOn: "essential-medications",
      showIf: "yes",
    },
  },
  {
    id: "essential-symptom-timeline",
    module: "SCREENING",
    order: 8,
    text: "When did your main health concerns begin?",
    type: "MULTIPLE_CHOICE",
    required: false,
    options: [
      "Less than 1 month ago",
      "1-3 months ago",
      "3-6 months ago",
      "6-12 months ago",
      "1-2 years ago",
      "2-5 years ago",
      "More than 5 years ago",
      "After a specific event (illness/injury/stress)",
    ],
  },

  // ========== DIGESTIVE MODULE (6 questions) ==========
  {
    id: "essential-bloating",
    module: "DIGESTIVE",
    order: 10,
    text: "How often do you experience bloating?",
    type: "FREQUENCY",
    required: true,
    options: ["Never", "Rarely", "Sometimes", "Often", "Always"],
  },
  {
    id: "essential-bowel-regularity",
    module: "DIGESTIVE",
    order: 9,
    text: "Do you have regular daily bowel movements?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-bowel-issues",
    module: "DIGESTIVE",
    order: 9.1,
    text: "Select your bowel movement patterns",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Constipation (less than 1x daily)",
      "Diarrhea (loose/watery)",
      "Alternating constipation/diarrhea",
      "Straining",
      "Incomplete evacuation",
      "Urgency",
      "Blood in stool",
      "Mucus in stool",
      "Pencil-thin stools",
      "Less than 3x per week",
      "More than 3x per day",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-bowel-regularity",
      showIf: "no",
    },
  },
  {
    id: "essential-acid-reflux",
    module: "DIGESTIVE",
    order: 10,
    text: "How often do you experience acid reflux or heartburn?",
    type: "FREQUENCY",
    required: true,
    options: ["Never", "Rarely", "Sometimes", "Often", "Always"],
  },
  {
    id: "essential-appetite",
    module: "DIGESTIVE",
    order: 11,
    text: "Rate your appetite",
    type: "LIKERT_SCALE",
    required: true,
    scale: {
      min: 0,
      max: 5,
      minLabel: "No appetite",
      maxLabel: "Excessive appetite",
    },
  },
  {
    id: "essential-stomach-pain",
    module: "DIGESTIVE",
    order: 12,
    text: "Do you experience stomach pain or cramping?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-stomach-pain-details",
    module: "DIGESTIVE",
    order: 12.1,
    text: "When does stomach pain occur?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Before meals",
      "During meals",
      "After meals",
      "Empty stomach",
      "Upper abdomen",
      "Lower abdomen",
      "Left side",
      "Right side",
      "Sharp pain",
      "Dull ache",
      "Burning sensation",
      "Cramping",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-stomach-pain",
      showIf: "yes",
    },
  },
  {
    id: "essential-food-reactions",
    module: "DIGESTIVE",
    order: 13,
    text: "Do certain foods trigger immediate digestive symptoms?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-food-reactions-list",
    module: "DIGESTIVE",
    order: 13.1,
    text: "What happens when you eat trigger foods?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Immediate bloating",
      "Gas within 30 minutes",
      "Stomach pain",
      "Diarrhea",
      "Constipation",
      "Heartburn",
      "Nausea",
      "Headache",
      "Skin reactions",
      "Fatigue",
      "Brain fog",
      "Joint pain",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-food-reactions",
      showIf: "yes",
    },
  },

  // ========== ENERGY MODULE (5 questions) ==========
  {
    id: "essential-morning-energy",
    module: "ENERGY",
    order: 15,
    text: "How is your energy when you wake up?",
    type: "MULTIPLE_CHOICE",
    required: true,
    options: [
      "Refreshed and ready",
      "Takes time to wake up",
      "Exhausted even after sleep",
    ],
  },
  {
    id: "essential-afternoon-crash",
    module: "ENERGY",
    order: 16,
    text: "Do you experience an afternoon energy crash?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-afternoon-crash-details",
    module: "ENERGY",
    order: 16.1,
    text: "When do energy crashes typically occur?",
    type: "MULTIPLE_CHOICE",
    required: false,
    options: [
      "30 minutes after eating",
      "1 hour after eating",
      "2 hours after eating",
      "3+ hours after eating",
      "After specific foods (sugar/carbs)",
      "After large meals",
      "Mid-morning (10-11am)",
      "Mid-afternoon (2-4pm)",
      "Variable/unpredictable",
    ],
    conditionalLogic: {
      dependsOn: "essential-afternoon-crash",
      showIf: "yes",
    },
  },
  {
    id: "essential-exercise-recovery",
    module: "ENERGY",
    order: 17,
    text: "How well do you recover from exercise?",
    type: "MULTIPLE_CHOICE",
    required: true,
    options: [
      "Quick recovery (same day)",
      "Normal recovery (1-2 days)",
      "Slow recovery (3+ days)",
      "Don't exercise",
    ],
  },
  {
    id: "essential-brain-fog",
    module: "ENERGY",
    order: 18,
    text: "How often do you experience brain fog or mental fatigue?",
    type: "FREQUENCY",
    required: true,
    options: ["Never", "Rarely", "Sometimes", "Often", "Always"],
  },
  {
    id: "essential-caffeine-need",
    module: "ENERGY",
    order: 19,
    text: "Do you need caffeine to function during the day?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-caffeine-details",
    module: "ENERGY",
    order: 19.1,
    text: "How much caffeine do you consume daily?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "1 cup coffee",
      "2-3 cups coffee",
      "4+ cups coffee",
      "Energy drinks",
      "Tea (black/green)",
      "Soda/Cola",
      "Pre-workout supplements",
      "Headache if I skip",
      "Fatigue if I skip",
      "Need it to wake up",
      "Need it after lunch",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-caffeine-need",
      showIf: "yes",
    },
  },

  // ========== IMMUNE MODULE (5 questions) ==========
  {
    id: "essential-sick-frequency",
    module: "IMMUNE",
    order: 20,
    text: "How often do you get sick (colds, flu, etc.)?",
    type: "MULTIPLE_CHOICE",
    required: true,
    options: [
      "Rarely (1-2 times/year)",
      "Sometimes (3-4 times/year)",
      "Often (5+ times/year)",
    ],
  },
  {
    id: "essential-autoimmune",
    module: "IMMUNE",
    order: 21,
    text: "Have you been diagnosed with any autoimmune conditions?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-autoimmune-list",
    module: "IMMUNE",
    order: 21.1,
    text: "Which autoimmune conditions do you have?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Hashimoto's Thyroiditis",
      "Graves' Disease",
      "Rheumatoid Arthritis",
      "Lupus (SLE)",
      "Multiple Sclerosis",
      "Type 1 Diabetes",
      "Celiac Disease",
      "Psoriasis",
      "Psoriatic Arthritis",
      "Inflammatory Bowel Disease",
      "Crohn's Disease",
      "Ulcerative Colitis",
      "Sjögren's Syndrome",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-autoimmune",
      showIf: "yes",
    },
  },
  {
    id: "essential-allergies",
    module: "IMMUNE",
    order: 22,
    text: "Do you have environmental allergies (pollen, dust, pets)?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-allergies-list",
    module: "IMMUNE",
    order: 22.1,
    text: "What are you allergic to?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Pollen/Hay fever",
      "Dust mites",
      "Pet dander",
      "Mold",
      "Dairy",
      "Eggs",
      "Peanuts",
      "Tree nuts",
      "Shellfish",
      "Fish",
      "Wheat/Gluten",
      "Soy",
      "Penicillin",
      "Other medications",
      "Latex",
      "Insect stings",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-allergies",
      showIf: "yes",
    },
  },
  {
    id: "essential-wound-healing",
    module: "IMMUNE",
    order: 23,
    text: "How quickly do wounds or cuts heal?",
    type: "MULTIPLE_CHOICE",
    required: true,
    options: ["Very quickly", "Normal pace", "Slowly", "Very slowly"],
  },
  {
    id: "essential-inflammation",
    module: "IMMUNE",
    order: 24,
    text: "Do you have signs of chronic inflammation (joint pain, skin issues, etc.)?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-inflammation-details",
    module: "IMMUNE",
    order: 24.1,
    text: "Select your inflammation symptoms",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Joint pain - hands/fingers",
      "Joint pain - knees",
      "Joint pain - hips",
      "Joint pain - back",
      "Joint pain - shoulders",
      "Morning stiffness",
      "Swelling in joints",
      "Redness/warmth in joints",
      "Muscle aches",
      "General body pain",
      "Skin rashes",
      "Eczema",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-inflammation",
      showIf: "yes",
    },
  },
  {
    id: "essential-inflammation-frequency",
    module: "IMMUNE",
    order: 24.2,
    text: "How often do you experience inflammation symptoms?",
    type: "MULTIPLE_CHOICE",
    required: false,
    options: [
      "Daily",
      "4-6 times per week",
      "2-3 times per week",
      "Weekly",
      "A few times per month",
      "Monthly or less",
    ],
    conditionalLogic: {
      dependsOn: "essential-inflammation-details",
      showIf: "hasAnySelection",
    },
  },
  {
    id: "essential-inflammation-severity",
    module: "IMMUNE",
    order: 24.3,
    text: "Rate the severity of your inflammation symptoms at their worst",
    type: "LIKERT_SCALE",
    required: false,
    scale: { min: 0, max: 5, minLabel: "Mild", maxLabel: "Severe" },
    conditionalLogic: {
      dependsOn: "essential-inflammation-details",
      showIf: "hasAnySelection",
    },
  },

  // ========== HORMONAL MODULE (6 questions) ==========
  {
    id: "essential-mood-swings",
    module: "HORMONAL",
    order: 25,
    text: "How often do you experience mood swings?",
    type: "FREQUENCY",
    required: true,
    options: ["Never", "Rarely", "Sometimes", "Often", "Always"],
  },
  {
    id: "essential-weight-changes",
    module: "HORMONAL",
    order: 26,
    text: "Have you experienced unexplained weight changes recently?",
    type: "MULTIPLE_CHOICE",
    required: true,
    options: [
      "Significant weight loss",
      "Slight weight loss",
      "No change",
      "Slight weight gain",
      "Significant weight gain",
    ],
  },
  {
    id: "essential-temperature-regulation",
    module: "HORMONAL",
    order: 27,
    text: "Do you have trouble regulating body temperature (always hot or cold)?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-temperature-details",
    module: "HORMONAL",
    order: 27.1,
    text: "Select your temperature regulation issues",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Always feel cold",
      "Always feel hot",
      "Cold hands and feet",
      "Night sweats",
      "Hot flashes",
      "Temperature swings",
      "Sensitive to cold weather",
      "Sensitive to hot weather",
      "Excessive sweating",
      "Rarely sweat",
      "Chills",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-temperature-regulation",
      showIf: "yes",
    },
  },
  {
    id: "essential-libido",
    module: "HORMONAL",
    order: 28,
    text: "Rate your libido/sex drive",
    type: "LIKERT_SCALE",
    required: true,
    scale: { min: 0, max: 5, minLabel: "Non-existent", maxLabel: "Very high" },
  },
  {
    id: "essential-hair-skin",
    module: "HORMONAL",
    order: 29,
    text: "Have you noticed changes in hair or skin quality?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-hair-skin-details",
    module: "HORMONAL",
    order: 29.1,
    text: "Select the changes in your hair or skin",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Hair loss/thinning",
      "Hair texture changes",
      "Dry hair",
      "Oily hair",
      "Dry skin",
      "Oily skin",
      "Acne",
      "Adult acne",
      "Skin rashes",
      "Dark spots",
      "Brittle nails",
      "Started recently",
      "Gradual change",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-hair-skin",
      showIf: "yes",
    },
  },
  {
    id: "essential-sugar-cravings",
    module: "HORMONAL",
    order: 30,
    text: "How often do you have sugar or carb cravings?",
    type: "FREQUENCY",
    required: true,
    options: ["Never", "Rarely", "Sometimes", "Often", "Always"],
  },

  // ========== NEUROLOGICAL MODULE ==========
  {
    id: "essential-anxiety-mood",
    module: "NEUROLOGICAL",
    order: 31,
    text: "Do you experience anxiety or mood swings?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-anxiety-mood-details",
    module: "NEUROLOGICAL",
    order: 31.1,
    text: "Select your symptoms",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "General anxiety",
      "Panic attacks",
      "Social anxiety",
      "Depression",
      "Mood swings",
      "Irritability",
      "Difficulty concentrating",
      "Racing thoughts",
      "Worry/rumination",
      "Occurs daily",
      "Occurs weekly",
      "Stress-triggered",
      "No clear trigger",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-anxiety-mood",
      showIf: "yes",
    },
  },
  {
    id: "essential-anxiety-frequency",
    module: "NEUROLOGICAL",
    order: 31.2,
    text: "How often do you experience anxiety or mood issues?",
    type: "MULTIPLE_CHOICE",
    required: false,
    options: [
      "Multiple times daily",
      "Daily",
      "Several times per week",
      "Weekly",
      "A few times per month",
      "Monthly or less",
    ],
    conditionalLogic: {
      dependsOn: "essential-anxiety-mood-details",
      showIf: "hasAnySelection",
    },
  },
  {
    id: "essential-anxiety-impact",
    module: "NEUROLOGICAL",
    order: 31.3,
    text: "How much do these symptoms interfere with your daily activities?",
    type: "LIKERT_SCALE",
    required: false,
    scale: {
      min: 0,
      max: 5,
      minLabel: "No interference",
      maxLabel: "Unable to function",
    },
    conditionalLogic: {
      dependsOn: "essential-anxiety-mood-details",
      showIf: "hasAnySelection",
    },
  },

  // ========== CARDIOVASCULAR MODULE ==========
  {
    id: "essential-breath-issues",
    module: "CARDIOVASCULAR",
    order: 32,
    text: "Do you experience shortness of breath with mild exertion?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-breath-details",
    module: "CARDIOVASCULAR",
    order: 32.1,
    text: "When does shortness of breath occur?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Walking on flat ground",
      "Walking uphill",
      "Climbing one flight of stairs",
      "Climbing multiple flights",
      "During exercise",
      "At rest",
      "When lying down",
      "During stress/anxiety",
      "In cold weather",
      "With allergies",
      "At night",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-breath-issues",
      showIf: "yes",
    },
  },
  {
    id: "essential-heart-family",
    module: "CARDIOVASCULAR",
    order: 33,
    text: "Do you have a family history of heart disease?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-heart-family-details",
    module: "CARDIOVASCULAR",
    order: 33.1,
    text: "Which heart conditions in your family?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Heart attack - parent",
      "Heart attack - sibling",
      "Heart attack - grandparent",
      "Stroke - parent",
      "Stroke - sibling",
      "Stroke - grandparent",
      "High blood pressure",
      "High cholesterol",
      "Atrial fibrillation",
      "Heart failure",
      "Bypass surgery",
      "Stent placement",
      "Sudden cardiac death",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-heart-family",
      showIf: "yes",
    },
  },

  // ========== DETOX MODULE ==========
  {
    id: "essential-chemical-sensitivity",
    module: "DETOX",
    order: 34,
    text: "Do you have sensitivities to chemicals, perfumes, or smoke?",
    type: "YES_NO",
    required: true,
  },
  {
    id: "essential-chemical-sensitivity-list",
    module: "DETOX",
    order: 34.1,
    text: "What triggers your sensitivities?",
    type: "MULTI_SELECT",
    required: false,
    options: [
      "Perfumes/Fragrances",
      "Cigarette smoke",
      "Cleaning products",
      "Laundry detergent",
      "Air fresheners",
      "Gasoline/Exhaust",
      "Paint/New carpet",
      "Pesticides",
      "Chlorine/Pool chemicals",
      "Causes headaches",
      "Causes breathing issues",
      "Causes nausea",
      "Causes skin reactions",
      "Other",
    ],
    conditionalLogic: {
      dependsOn: "essential-chemical-sensitivity",
      showIf: "yes",
    },
  },
];

// Helper function to get only essential questions
export function getEssentialQuestions() {
  return ESSENTIAL_QUESTIONS;
}

// Helper function to check if using essential mode
export function isEssentialMode() {
  // You can toggle this based on environment variable or setting
  return process.env.NEXT_PUBLIC_ESSENTIAL_MODE === "true" || true; // Default to true for testing
}

// Function to filter questions to only essential ones
export function filterToEssential(allQuestions: any[]) {
  const essentialIds = new Set(ESSENTIAL_QUESTIONS.map((q) => q.id));
  return allQuestions.filter((q) => essentialIds.has(q.id));
}
