/**
 * Extended Comprehensive Questions - Additional questions for complete 270+ assessment
 * 
 * This file contains additional questions to expand the comprehensive assessment
 * to the target 270+ questions across all functional medicine categories.
 */

import { ComprehensiveQuestion } from './comprehensive-questions';

// Extended question bank to reach target 270+ questions
export const EXTENDED_COMPREHENSIVE_QUESTIONS: ComprehensiveQuestion[] = [
  
  // ========================================
  // DIGESTIVE SYSTEM - ENZYME FUNCTION (8 questions)
  // ========================================
  {
    id: 20,
    systemCategory: 'digestive',
    subCategory: 'enzyme_function',
    questionText: 'How often do you see undigested food particles in your stool?',
    helpText: 'Undigested food suggests insufficient digestive enzyme production',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    reverseScore: true,
    questionCluster: 'enzyme_deficiency',
    rootCauseIndicator: true,
    clinicalNotes: 'Visible undigested food indicates severe enzyme deficiency',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 21,
    systemCategory: 'digestive',
    subCategory: 'enzyme_function',
    questionText: 'How often do you feel overly full or heavy after eating protein-rich meals?',
    scaleType: 'frequency',
    diagnosticWeight: 2.1,
    reverseScore: true,
    questionCluster: 'protein_digestion',
    rootCauseIndicator: true,
    clinicalNotes: 'Protein digestion difficulty indicates pepsin/HCl deficiency',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 22,
    systemCategory: 'digestive',
    subCategory: 'enzyme_function',
    questionText: 'How severe is your discomfort after eating fatty or greasy foods?',
    scaleType: 'severity',
    diagnosticWeight: 2.2,
    reverseScore: true,
    questionCluster: 'fat_digestion',
    rootCauseIndicator: true,
    clinicalNotes: 'Fat intolerance indicates bile/lipase deficiency',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 23,
    systemCategory: 'digestive',
    subCategory: 'enzyme_function',
    questionText: 'How much do digestive enzymes improve your symptoms?',
    scaleType: 'level',
    diagnosticWeight: 2.6,
    reverseScore: false,
    questionCluster: 'enzyme_supplement_response',
    rootCauseIndicator: true,
    clinicalNotes: 'Improvement with enzymes confirms enzyme deficiency diagnosis',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // DIGESTIVE SYSTEM - STOMACH ACID (10 questions)
  // ========================================
  {
    id: 30,
    systemCategory: 'digestive',
    subCategory: 'stomach_acid',
    questionText: 'How often do you experience belching or burping after meals?',
    scaleType: 'frequency',
    diagnosticWeight: 2.0,
    reverseScore: true,
    questionCluster: 'low_stomach_acid',
    rootCauseIndicator: true,
    clinicalNotes: 'Excessive belching often indicates low stomach acid and poor protein digestion',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 31,
    systemCategory: 'digestive',
    subCategory: 'stomach_acid',
    questionText: 'How much do you feel better when taking digestive enzymes or apple cider vinegar?',
    scaleType: 'level',
    diagnosticWeight: 2.7,
    reverseScore: false,
    questionCluster: 'acid_enzyme_response',
    rootCauseIndicator: true,
    clinicalNotes: 'Improvement with acid/enzymes confirms hypochlorhydria diagnosis',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 32,
    systemCategory: 'digestive',
    subCategory: 'stomach_acid',
    questionText: 'How often do you feel like food sits in your stomach too long after eating?',
    scaleType: 'frequency',
    diagnosticWeight: 2.1,
    reverseScore: true,
    questionCluster: 'gastric_emptying',
    rootCauseIndicator: true,
    clinicalNotes: 'Delayed gastric emptying often due to low stomach acid',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // ENERGY SYSTEM - MITOCHONDRIAL FUNCTION (15 questions)
  // ========================================
  {
    id: 60,
    systemCategory: 'energy',
    subCategory: 'mitochondrial',
    questionText: 'How much does exercise make you feel worse rather than better?',
    helpText: 'Exercise intolerance can indicate mitochondrial dysfunction',
    scaleType: 'level',
    diagnosticWeight: 2.6,
    reverseScore: true,
    questionCluster: 'exercise_intolerance',
    rootCauseIndicator: true,
    clinicalNotes: 'Exercise intolerance is hallmark of mitochondrial dysfunction',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 61,
    systemCategory: 'energy',
    subCategory: 'mitochondrial',
    questionText: 'How often do you experience muscle fatigue that seems disproportionate to activity?',
    scaleType: 'frequency',
    diagnosticWeight: 2.3,
    reverseScore: true,
    questionCluster: 'muscle_energy_dysfunction',
    rootCauseIndicator: true,
    clinicalNotes: 'Muscle fatigue indicates cellular energy production problems',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 62,
    systemCategory: 'energy',
    subCategory: 'mitochondrial',
    questionText: 'How long does it take you to recover from physical exertion?',
    helpText: 'Recovery time reflects mitochondrial capacity and cellular energy production',
    scaleType: 'level',
    diagnosticWeight: 2.2,
    reverseScore: true,
    questionCluster: 'recovery_capacity',
    rootCauseIndicator: true,
    clinicalNotes: 'Slow recovery indicates mitochondrial dysfunction and poor energy production',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // ENERGY SYSTEM - BLOOD SUGAR REGULATION (12 questions)
  // ========================================
  {
    id: 75,
    systemCategory: 'energy',
    subCategory: 'blood_sugar',
    questionText: 'How often do you experience energy crashes 2-4 hours after eating?',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    reverseScore: true,
    questionCluster: 'reactive_hypoglycemia',
    rootCauseIndicator: true,
    clinicalNotes: 'Post-meal energy crashes indicate reactive hypoglycemia and insulin dysfunction',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 76,
    systemCategory: 'energy',
    subCategory: 'blood_sugar',
    questionText: 'How much do you crave sugar or carbohydrates when your energy drops?',
    scaleType: 'level',
    diagnosticWeight: 2.1,
    reverseScore: true,
    questionCluster: 'sugar_craving_patterns',
    rootCauseIndicator: false,
    clinicalNotes: 'Sugar cravings indicate blood sugar instability and possibly dysbiotic bacteria',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 77,
    systemCategory: 'energy',
    subCategory: 'blood_sugar',
    questionText: 'How shaky, lightheaded, or anxious do you get when you skip meals?',
    scaleType: 'severity',
    diagnosticWeight: 2.3,
    reverseScore: true,
    questionCluster: 'hypoglycemic_symptoms',
    rootCauseIndicator: true,
    clinicalNotes: 'Hypoglycemic symptoms indicate poor glucose regulation and insulin sensitivity issues',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // HORMONAL SYSTEM - SEX HORMONES (15 questions)
  // ========================================
  {
    id: 120,
    systemCategory: 'hormonal',
    subCategory: 'sex_hormones',
    questionText: 'How severe are your PMS symptoms (mood swings, bloating, cravings)?',
    helpText: 'PMS severity often indicates estrogen/progesterone imbalance',
    scaleType: 'severity',
    diagnosticWeight: 2.3,
    reverseScore: true,
    questionCluster: 'estrogen_dominance',
    rootCauseIndicator: true,
    clinicalNotes: 'Severe PMS indicates estrogen dominance or progesterone deficiency',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 121,
    systemCategory: 'hormonal',
    subCategory: 'sex_hormones',
    questionText: 'How much has your libido decreased compared to previous years?',
    scaleType: 'level',
    diagnosticWeight: 2.0,
    reverseScore: true,
    questionCluster: 'sex_hormone_decline',
    rootCauseIndicator: true,
    clinicalNotes: 'Decreased libido indicates sex hormone deficiency or imbalance',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 122,
    systemCategory: 'hormonal',
    subCategory: 'sex_hormones',
    questionText: 'How often do you experience breast tenderness or fibrocystic changes?',
    scaleType: 'frequency',
    diagnosticWeight: 2.1,
    reverseScore: true,
    questionCluster: 'estrogen_dominance',
    rootCauseIndicator: true,
    clinicalNotes: 'Breast tenderness indicates estrogen dominance and poor hormone metabolism',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // TOXIC LOAD SYSTEM - HEAVY METALS (8 questions)
  // ========================================
  {
    id: 230,
    systemCategory: 'toxic_load',
    subCategory: 'heavy_metals',
    questionText: 'How many amalgam (silver) dental fillings do you have or have you had?',
    helpText: 'Amalgam fillings are a major source of chronic mercury exposure',
    scaleType: 'level',
    diagnosticWeight: 1.9,
    reverseScore: true,
    questionCluster: 'mercury_exposure',
    rootCauseIndicator: true,
    clinicalNotes: 'Amalgam fillings major source of mercury toxicity affecting neurological function',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 231,
    systemCategory: 'toxic_load',
    subCategory: 'heavy_metals',
    questionText: 'How often do you eat large fish (tuna, swordfish, shark) or seafood?',
    scaleType: 'frequency',
    diagnosticWeight: 1.6,
    reverseScore: true,
    questionCluster: 'dietary_mercury_exposure',
    rootCauseIndicator: false,
    clinicalNotes: 'Large fish consumption increases mercury burden',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // INFLAMMATORY SYSTEM - AUTOIMMUNE INDICATORS (10 questions)
  // ========================================
  {
    id: 170,
    systemCategory: 'inflammatory',
    subCategory: 'autoimmune',
    questionText: 'How often do you experience joint pain that moves from joint to joint?',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    reverseScore: true,
    questionCluster: 'migratory_joint_pain',
    rootCauseIndicator: true,
    clinicalNotes: 'Migratory joint pain classic sign of systemic inflammation from gut dysfunction',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 171,
    systemCategory: 'inflammatory',
    subCategory: 'autoimmune',
    questionText: 'How often do you have skin issues (eczema, rashes, acne) that flare with certain foods?',
    scaleType: 'frequency',
    diagnosticWeight: 2.2,
    reverseScore: true,
    questionCluster: 'food_inflammatory_response',
    rootCauseIndicator: true,
    clinicalNotes: 'Food-triggered skin issues indicate intestinal permeability and systemic inflammation',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 172,
    systemCategory: 'inflammatory',
    subCategory: 'autoimmune',
    questionText: 'How often do you develop new allergies or food sensitivities?',
    scaleType: 'frequency',
    diagnosticWeight: 2.3,
    reverseScore: true,
    questionCluster: 'progressive_reactivity',
    rootCauseIndicator: true,
    clinicalNotes: 'Developing new sensitivities indicates immune system dysfunction and intestinal permeability',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // NEUROLOGICAL SYSTEM - BRAIN FOG & COGNITIVE (12 questions)
  // ========================================
  {
    id: 190,
    systemCategory: 'neurological',
    subCategory: 'brain_fog',
    questionText: 'How often do you have difficulty concentrating or brain fog?',
    scaleType: 'frequency',
    diagnosticWeight: 2.0,
    reverseScore: true,
    questionCluster: 'cognitive_dysfunction',
    rootCauseIndicator: true,
    clinicalNotes: 'Brain fog indicates neuroinflammation, often from gut dysfunction',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 191,
    systemCategory: 'neurological',
    subCategory: 'brain_fog',
    questionText: 'How much does your mental clarity worsen after eating certain foods?',
    scaleType: 'level',
    diagnosticWeight: 2.4,
    reverseScore: true,
    questionCluster: 'food_brain_connection',
    rootCauseIndicator: true,
    clinicalNotes: 'Food-triggered brain fog indicates gut-brain axis dysfunction',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // MODERN FM - SEED OIL DAMAGE (10 questions)
  // ========================================
  {
    id: 270,
    systemCategory: 'modern_fm',
    subCategory: 'seed_oil_damage',
    questionText: 'How much do you react differently to restaurant food vs. home-cooked meals?',
    helpText: 'Restaurant foods typically contain high amounts of inflammatory seed oils',
    scaleType: 'level',
    diagnosticWeight: 1.8,
    reverseScore: true,
    questionCluster: 'restaurant_food_reaction',
    rootCauseIndicator: false,
    clinicalNotes: 'Restaurant food reactions often due to seed oil content and inflammatory preparation',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
    testingNotes: 'Modern insight - seed oils major inflammatory trigger',
  },
  {
    id: 271,
    systemCategory: 'modern_fm',
    subCategory: 'seed_oil_damage',
    questionText: 'How much do your energy and mood improve on whole foods vs. processed foods?',
    scaleType: 'level',
    diagnosticWeight: 2.0,
    reverseScore: false,
    questionCluster: 'whole_foods_response',
    rootCauseIndicator: true,
    clinicalNotes: 'Dramatic improvement on whole foods indicates inflammatory food reactions',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
  },
  {
    id: 272,
    systemCategory: 'modern_fm',
    subCategory: 'seed_oil_damage',
    questionText: 'How much inflammation do you notice after eating fried or processed foods?',
    scaleType: 'level',
    diagnosticWeight: 2.2,
    reverseScore: true,
    questionCluster: 'processed_food_inflammation',
    rootCauseIndicator: true,
    clinicalNotes: 'Inflammatory response to processed foods indicates omega-6 fatty acid sensitivity',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
    testingNotes: 'Critical modern FM question - processed food inflammation',
  },

  // ========================================
  // MODERN FM - MOLD & BIOTOXIN ILLNESS (12 questions)
  // ========================================
  {
    id: 280,
    systemCategory: 'modern_fm',
    subCategory: 'mold_biotoxin',
    questionText: 'How much do your symptoms worsen in moldy or water-damaged buildings?',
    helpText: 'Mold sensitivity can indicate biotoxin illness and impaired detoxification',
    scaleType: 'level',
    diagnosticWeight: 2.2,
    reverseScore: true,
    questionCluster: 'mold_sensitivity',
    rootCauseIndicator: true,
    clinicalNotes: 'Mold reactivity indicates biotoxin illness - increasing modern health concern',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
    testingNotes: 'Important modern FM question - mold exposure increasingly common',
  },
  {
    id: 281,
    systemCategory: 'modern_fm',
    subCategory: 'mold_biotoxin',
    questionText: 'How often do you experience "weird" or hard-to-describe symptoms that doctors dismiss?',
    helpText: 'Biotoxin illness often presents with unusual symptoms that are difficult to diagnose',
    scaleType: 'frequency',
    diagnosticWeight: 1.9,
    reverseScore: true,
    questionCluster: 'biotoxin_symptom_pattern',
    rootCauseIndicator: true,
    clinicalNotes: 'Biotoxin illness creates unusual symptom patterns often missed in conventional medicine',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
    testingNotes: 'Monitor for specificity - many conditions can cause unusual symptoms',
  },
  {
    id: 282,
    systemCategory: 'modern_fm',
    subCategory: 'mold_biotoxin',
    questionText: 'How much do you feel better when you leave your home/work environment for extended periods?',
    scaleType: 'level',
    diagnosticWeight: 2.4,
    reverseScore: false,
    questionCluster: 'environmental_improvement',
    rootCauseIndicator: true,
    clinicalNotes: 'Environmental improvement strongly suggests biotoxin or mold exposure at primary location',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
  },

  // ========================================
  // MODERN FM - CIRCADIAN DISRUPTION (8 questions)
  // ========================================
  {
    id: 290,
    systemCategory: 'modern_fm',
    subCategory: 'circadian_disruption',
    questionText: 'How much artificial light exposure do you get in the evening (screens, LED lights)?',
    helpText: 'Evening light exposure disrupts natural circadian rhythms and hormone production',
    scaleType: 'level',
    diagnosticWeight: 1.7,
    reverseScore: true,
    questionCluster: 'evening_light_exposure',
    rootCauseIndicator: true,
    clinicalNotes: 'Evening light exposure disrupts melatonin production and circadian rhythm',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
    testingNotes: 'Modern FM priority - light pollution major health disruptor',
  },
  {
    id: 291,
    systemCategory: 'modern_fm',
    subCategory: 'circadian_disruption',
    questionText: 'How much does your sleep quality improve when you avoid screens 2+ hours before bed?',
    scaleType: 'level',
    diagnosticWeight: 2.0,
    reverseScore: false,
    questionCluster: 'screen_sleep_correlation',
    rootCauseIndicator: true,
    clinicalNotes: 'Sleep improvement without screens confirms circadian disruption from blue light',
    modernFMUpdate: true,
    version: 1,
    isActive: true,
  },

  // ========================================
  // CARDIOVASCULAR SYSTEM - CIRCULATION & HEART (12 questions)
  // ========================================
  {
    id: 300,
    systemCategory: 'cardiovascular',
    subCategory: 'circulation',
    questionText: 'How often are your hands and feet cold compared to the rest of your body?',
    scaleType: 'frequency',
    diagnosticWeight: 1.9,
    reverseScore: true,
    questionCluster: 'peripheral_circulation',
    rootCauseIndicator: true,
    clinicalNotes: 'Cold extremities indicate poor circulation, often related to thyroid or adrenal dysfunction',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 301,
    systemCategory: 'cardiovascular',
    subCategory: 'heart_function',
    questionText: 'How often do you experience heart palpitations or irregular heartbeat?',
    scaleType: 'frequency',
    diagnosticWeight: 2.1,
    reverseScore: true,
    questionCluster: 'heart_rhythm_disruption',
    rootCauseIndicator: true,
    clinicalNotes: 'Palpitations can indicate magnesium deficiency, stress, or thyroid dysfunction',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },
  {
    id: 302,
    systemCategory: 'cardiovascular',
    subCategory: 'circulation',
    questionText: 'How often do you feel dizzy or lightheaded when standing up quickly?',
    scaleType: 'frequency',
    diagnosticWeight: 2.0,
    reverseScore: true,
    questionCluster: 'orthostatic_dysfunction',
    rootCauseIndicator: true,
    clinicalNotes: 'Orthostatic symptoms indicate adrenal dysfunction or blood volume issues',
    modernFMUpdate: false,
    version: 1,
    isActive: true,
  },

  // ========================================
  // ADDITIONAL COMPREHENSIVE QUESTIONS
  // Continue building to reach 270+ target...
  // ========================================
];

// Helper function to merge with base questions
export function getAllComprehensiveQuestions(): ComprehensiveQuestion[] {
  // Import base questions
  const baseQuestions = require('./comprehensive-questions').COMPREHENSIVE_QUESTIONS;
  
  // Merge base + extended questions
  const allQuestions = [...baseQuestions, ...EXTENDED_COMPREHENSIVE_QUESTIONS];
  
  // Sort by ID to maintain order
  return allQuestions.sort((a, b) => a.id - b.id);
}

// Export statistics for the extended question set
export const EXTENDED_STATISTICS = {
  baseQuestions: 15, // From comprehensive-questions.ts
  extendedQuestions: EXTENDED_COMPREHENSIVE_QUESTIONS.length,
  totalQuestions: 15 + EXTENDED_COMPREHENSIVE_QUESTIONS.length,
  targetQuestions: 270,
  completionPercentage: Math.round(((15 + EXTENDED_COMPREHENSIVE_QUESTIONS.length) / 270) * 100),
};

// Question development roadmap
export const DEVELOPMENT_ROADMAP = {
  phase1: {
    name: 'Foundation Questions',
    target: 50,
    current: EXTENDED_STATISTICS.totalQuestions,
    priority: ['digestive', 'energy', 'hormonal'],
    timeline: '2-4 weeks',
  },
  phase2: {
    name: 'Advanced Systems',
    target: 150,
    priority: ['toxic_load', 'inflammatory', 'neurological'],
    timeline: '4-8 weeks',
  },
  phase3: {
    name: 'Modern FM Categories',
    target: 270,
    priority: ['modern_fm', 'cardiovascular'],
    timeline: '8-12 weeks',
  },
};
