import { AssessmentQuestion } from "../../types";
import { BodySystems } from "../../body-systems";

export const endocrineQuestions: AssessmentQuestion[] = [
  // Energy & Fatigue
  {
    id: "ENDO001",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "How would you rate your overall energy level?",
    type: "LIKERT_SCALE",
    scaleMin: "No energy",
    scaleMax: "Abundant energy",
    scoringWeight: 2.0,
    clinicalRelevance: ["energy_metabolism", "thyroid", "adrenal"],
  },
  {
    id: "ENDO002",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you experience energy crashes during the day?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "daily", label: "Daily", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["blood_sugar", "adrenal", "cortisol_rhythm"],
  },
  {
    id: "ENDO003",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "What time of day is your energy lowest?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "morning", label: "Morning", score: 2 },
      { value: "midmorning", label: "Mid-morning", score: 1 },
      { value: "afternoon", label: "Afternoon", score: 1 },
      { value: "evening", label: "Evening", score: 0 },
      { value: "all_day", label: "Low all day", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["circadian_rhythm", "cortisol", "thyroid"],
  },

  // Blood Sugar
  {
    id: "ENDO004",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you get shaky, weak, or irritable if you miss meals?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 1 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["hypoglycemia", "insulin_resistance", "blood_sugar"],
  },
  {
    id: "ENDO005",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you crave sugar or carbohydrates?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["blood_sugar_dysregulation", "candida", "insulin"],
  },
  {
    id: "ENDO006",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Have you been diagnosed with diabetes or prediabetes?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "no", label: "No", score: 0 },
      { value: "prediabetes", label: "Prediabetes", score: 2 },
      { value: "type2", label: "Type 2 diabetes", score: 3 },
      { value: "type1", label: "Type 1 diabetes", score: 3 },
      { value: "gestational", label: "Gestational diabetes (past)", score: 1 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["diabetes", "glucose_metabolism", "insulin_resistance"],
  },

  // Thyroid
  {
    id: "ENDO007",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Are you always cold or have cold hands/feet?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "extremely", label: "Yes, extremely", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["hypothyroid", "circulation", "metabolism"],
  },
  {
    id: "ENDO008",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Have you noticed thinning hair or hair loss?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "significant", label: "Yes, significant", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["thyroid", "hormones", "nutrient_deficiency"],
  },
  {
    id: "ENDO009",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you have dry skin despite adequate hydration?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very_dry", label: "Yes, very dry", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["hypothyroid", "essential_fatty_acids", "hydration"],
  },
  {
    id: "ENDO010",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Have you been diagnosed with thyroid problems?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "no", label: "No", score: 0 },
      { value: "hypo", label: "Hypothyroid", score: 3 },
      { value: "hyper", label: "Hyperthyroid", score: 3 },
      { value: "hashimotos", label: "Hashimoto's", score: 3 },
      { value: "nodules", label: "Thyroid nodules", score: 2 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["thyroid_disease", "autoimmune", "metabolism"],
  },

  // Weight Management
  {
    id: "ENDO011",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Have you had unexplained weight gain?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "significant", label: "Yes, significant", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["metabolism", "thyroid", "insulin_resistance"],
  },
  {
    id: "ENDO012",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Is it difficult for you to lose weight?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "impossible", label: "Yes, seems impossible", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["metabolic_resistance", "hormones", "thyroid"],
  },
  {
    id: "ENDO013",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you carry weight mainly in your midsection?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "na", label: "No weight issues", score: 0 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["cortisol", "insulin_resistance", "metabolic_syndrome"],
  },

  // Adrenal/Stress
  {
    id: "ENDO014",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you feel wired but tired?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["adrenal_dysfunction", "cortisol", "HPA_axis"],
  },
  {
    id: "ENDO015",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you rely on caffeine to get through the day?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "heavily", label: "Yes, heavily", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["adrenal_fatigue", "energy", "dependence"],
  },
  {
    id: "ENDO016",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you get a second wind at night?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "always", label: "Yes, always", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["cortisol_rhythm", "circadian", "adrenal"],
  },

  // Female Hormones
  {
    id: "ENDO017",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you have PMS symptoms?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "mild", label: "Mild", score: 1 },
      { value: "moderate", label: "Moderate", score: 2 },
      { value: "severe", label: "Severe", score: 3 },
      { value: "na", label: "Not applicable", score: 0 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["hormone_balance", "estrogen", "progesterone"],
    genderSpecific: "female",
  },
  {
    id: "ENDO018",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you have heavy or painful periods?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "na", label: "Not applicable", score: 0 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["estrogen_dominance", "prostaglandins", "inflammation"],
    genderSpecific: "female",
  },
  {
    id: "ENDO019",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Are you experiencing menopausal symptoms?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "no", label: "No", score: 0 },
      { value: "peri", label: "Perimenopause", score: 2 },
      { value: "meno", label: "Menopause", score: 2 },
      { value: "post", label: "Post-menopause", score: 1 },
      { value: "na", label: "Not applicable", score: 0 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["menopause", "hormone_transition", "estrogen"],
    genderSpecific: "female",
  },

  // Male Hormones
  {
    id: "ENDO020",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Have you noticed decreased libido or sex drive?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "significant", label: "Yes, significant", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["testosterone", "libido", "hormones"],
  },
  {
    id: "ENDO021",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you have erectile dysfunction?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["erectile_dysfunction", "vascular", "testosterone"],
    genderSpecific: "male",
  },
  {
    id: "ENDO022",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Have you lost muscle mass or strength?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "significant", label: "Yes, significant", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["testosterone", "sarcopenia", "aging"],
  },

  // Temperature Regulation
  {
    id: "ENDO023",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you have hot flashes or night sweats?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "daily", label: "Daily", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["vasomotor_symptoms", "estrogen", "menopause"],
  },
  {
    id: "ENDO024",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you sweat excessively or hardly at all?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "normal", label: "Normal sweating", score: 0 },
      { value: "excessive", label: "Excessive sweating", score: 2 },
      { value: "minimal", label: "Hardly sweat at all", score: 2 },
      { value: "night_only", label: "Only night sweats", score: 2 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["autonomic", "thyroid", "hormones"],
  },

  // Metabolic
  {
    id: "ENDO025",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you urinate frequently?",
    type: "FREQUENCY",
    options: [
      { value: "normal", label: "Normal (4-7x/day)", score: 0 },
      { value: "8-10", label: "8-10 times/day", score: 1 },
      { value: "11-15", label: "11-15 times/day", score: 2 },
      { value: "over15", label: "Over 15 times/day", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["diabetes", "bladder", "prostate"],
  },
  {
    id: "ENDO026",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Are you excessively thirsty?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "constantly", label: "Yes, constantly", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["diabetes", "blood_sugar", "electrolytes"],
  },

  // Growth & Development
  {
    id: "ENDO027",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you bruise easily?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very_easily", label: "Yes, very easily", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["cortisol", "vitamin_C", "capillary_fragility"],
  },
  {
    id: "ENDO028",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you have stretch marks (not from pregnancy)?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "many", label: "Yes, many", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["cortisol", "cushing", "rapid_weight_change"],
  },

  // Sleep & Recovery
  {
    id: "ENDO029",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you wake up tired despite adequate sleep?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["sleep_quality", "cortisol", "recovery"],
  },
  {
    id: "ENDO030",
    module: "SCREENING",
    bodySystem: BodySystems.ENDOCRINE,
    text: "Do you need more than 8 hours of sleep to feel rested?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "never_rested", label: "Never feel rested", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["recovery", "adrenal_fatigue", "thyroid"],
  },
];
