import { AssessmentQuestion } from "../../types";
import { BodySystems } from "../../body-systems";

export const genitourinaryQuestions: AssessmentQuestion[] = [
  // Urinary Frequency
  {
    id: "GU001",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "How often do you urinate during the day?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "3-4", label: "3-4 times", score: 0 },
      { value: "5-7", label: "5-7 times", score: 0 },
      { value: "8-10", label: "8-10 times", score: 1 },
      { value: "11-15", label: "11-15 times", score: 2 },
      { value: "over15", label: "Over 15 times", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["urinary_frequency", "bladder_health", "diabetes"],
  },
  {
    id: "GU002",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you wake up at night to urinate?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "once", label: "Once", score: 1 },
      { value: "2-3times", label: "2-3 times", score: 2 },
      { value: "4-5times", label: "4-5 times", score: 3 },
      { value: "more5", label: "More than 5 times", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["nocturia", "prostate", "sleep_disruption"],
  },

  // Urgency & Control
  {
    id: "GU003",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have urgent need to urinate?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["urinary_urgency", "overactive_bladder", "UTI"],
  },
  {
    id: "GU004",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you experience urinary incontinence (leaking)?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["incontinence", "pelvic_floor", "bladder_control"],
  },
  {
    id: "GU005",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you leak urine when coughing, sneezing, or laughing?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "often", label: "Yes, often", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["stress_incontinence", "pelvic_floor_weakness"],
  },

  // Stream & Flow
  {
    id: "GU006",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have difficulty starting urination?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 1 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["urinary_hesitancy", "prostate", "bladder_outlet"],
  },
  {
    id: "GU007",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Is your urine stream weak or interrupted?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very_weak", label: "Yes, very weak", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["weak_stream", "prostate_enlargement", "stricture"],
  },
  {
    id: "GU008",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you feel like your bladder doesn't empty completely?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "always", label: "Yes, always", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["incomplete_emptying", "retention", "prostate"],
  },

  // Pain & Discomfort
  {
    id: "GU009",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have pain or burning with urination?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["dysuria", "UTI", "inflammation"],
  },
  {
    id: "GU010",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have pelvic or lower abdominal pain?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["pelvic_pain", "interstitial_cystitis", "endometriosis"],
  },

  // Infections
  {
    id: "GU011",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you get frequent urinary tract infections (UTIs)?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely (less than 1/year)", score: 1 },
      { value: "1-2year", label: "1-2 per year", score: 2 },
      { value: "3-4year", label: "3-4 per year", score: 3 },
      { value: "monthly", label: "Monthly or more", score: 4 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["recurrent_UTI", "immune_function", "hygiene"],
  },
  {
    id: "GU012",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have recurrent yeast infections?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "few_year", label: "Few times a year", score: 2 },
      { value: "monthly", label: "Monthly", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["candida", "vaginal_health", "immune_dysfunction"],
    genderSpecific: "female",
  },

  // Kidney Function
  {
    id: "GU013",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have kidney stones or history of kidney stones?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "multiple", label: "Yes, multiple times", score: 4 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["kidney_stones", "calcium_metabolism", "oxalates"],
  },
  {
    id: "GU014",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have foamy or bubbly urine?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["proteinuria", "kidney_function", "diabetes"],
  },

  // Sexual Health
  {
    id: "GU015",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Have you noticed a decrease in libido (sex drive)?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "significant", label: "Yes, significant", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["libido", "hormones", "relationship_health"],
  },
  {
    id: "GU016",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have pain during intercourse?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["dyspareunia", "vaginal_dryness", "inflammation"],
  },

  // Female Specific
  {
    id: "GU017",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have vaginal dryness?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "severe", label: "Yes, severe", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["vaginal_dryness", "estrogen", "menopause"],
    genderSpecific: "female",
  },
  {
    id: "GU018",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have abnormal vaginal discharge?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "frequently", label: "Yes, frequently", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["vaginal_discharge", "infection", "pH_imbalance"],
    genderSpecific: "female",
  },

  // Male Specific
  {
    id: "GU019",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have prostate problems or enlarged prostate?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "suspected", label: "Suspected", score: 2 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["BPH", "prostate_health", "urinary_symptoms"],
    genderSpecific: "male",
  },
  {
    id: "GU020",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have testicular pain or swelling?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["testicular_health", "epididymitis", "varicocele"],
    genderSpecific: "male",
  },

  // Fertility
  {
    id: "GU021",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Have you had difficulty conceiving?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "na", label: "Not trying", score: 0 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["fertility", "hormones", "reproductive_health"],
  },
  {
    id: "GU022",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Have you had miscarriages?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "no", label: "No", score: 0 },
      { value: "one", label: "One", score: 2 },
      { value: "two", label: "Two", score: 3 },
      { value: "three_plus", label: "Three or more", score: 4 },
      { value: "na", label: "Not applicable", score: 0 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["pregnancy_loss", "hormones", "clotting"],
    genderSpecific: "female",
  },

  // Other Symptoms
  {
    id: "GU023",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Is your urine dark, cloudy, or strong-smelling?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["dehydration", "infection", "liver"],
  },
  {
    id: "GU024",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you see blood in your urine?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 4 },
      { value: "no", label: "No", score: 0 },
      { value: "occasionally", label: "Occasionally", score: 3 },
    ],
    scoringWeight: 2.5,
    clinicalRelevance: ["hematuria", "kidney_disease", "bladder_cancer"],
  },
  {
    id: "GU025",
    module: "SCREENING",
    bodySystem: BodySystems.GENITOURINARY,
    text: "Do you have swelling in your feet, ankles, or hands?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["edema", "kidney_function", "heart_failure"],
  },
];
