import { AssessmentQuestion } from "../../types";
import { BodySystems } from "../../body-systems";

export const musculoskeletalQuestions: AssessmentQuestion[] = [
  // Joint Pain
  {
    id: "MUSC001",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you experience joint pain or stiffness?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "daily", label: "Daily", score: 4 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["arthritis", "inflammation", "joint_health"],
  },
  {
    id: "MUSC002",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Which joints are most affected?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "none", label: "No joint pain", score: 0 },
      { value: "fingers", label: "Fingers/Hands", score: 2 },
      { value: "knees", label: "Knees", score: 2 },
      { value: "hips", label: "Hips", score: 2 },
      { value: "multiple", label: "Multiple joints", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["joint_distribution", "arthritis_type"],
    conditionalLogic: [
      {
        condition: "never",
        action: "skip",
        skipQuestions: ["MUSC002", "MUSC003"],
      },
    ],
  },
  {
    id: "MUSC003",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Is joint stiffness worse in the morning?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "na", label: "No stiffness", score: 0 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: [
      "inflammatory_arthritis",
      "rheumatoid",
      "osteoarthritis",
    ],
  },

  // Back Pain
  {
    id: "MUSC004",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have lower back pain?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["lumbar_pain", "disc_issues", "posture"],
  },
  {
    id: "MUSC005",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have upper back or neck pain?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["cervical_pain", "tension", "posture"],
  },
  {
    id: "MUSC006",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Does back pain radiate down your legs (sciatica)?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["sciatica", "nerve_compression", "disc_herniation"],
  },

  // Muscle Symptoms
  {
    id: "MUSC007",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you experience muscle pain or aches?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["myalgia", "fibromyalgia", "inflammation"],
  },
  {
    id: "MUSC008",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have muscle weakness?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "progressing", label: "Yes, getting worse", score: 4 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["muscle_weakness", "neuropathy", "myopathy"],
  },
  {
    id: "MUSC009",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you get muscle cramps or spasms?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "daily", label: "Daily", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["muscle_cramps", "electrolyte_imbalance", "magnesium"],
  },

  // Movement & Flexibility
  {
    id: "MUSC010",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you feel stiff or inflexible?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very", label: "Yes, very stiff", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["flexibility", "fascia", "movement_quality"],
  },
  {
    id: "MUSC011",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Is it difficult to bend over and touch your toes?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "impossible", label: "Yes, impossible", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["hamstring_flexibility", "back_health"],
  },
  {
    id: "MUSC012",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have difficulty with balance or coordination?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["balance", "proprioception", "neurological"],
  },

  // Injury & Recovery
  {
    id: "MUSC013",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you injure easily (strains, sprains)?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very_easily", label: "Yes, very easily", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["connective_tissue", "collagen", "injury_prone"],
  },
  {
    id: "MUSC014",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do injuries take a long time to heal?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very_long", label: "Yes, very long", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["healing_capacity", "inflammation", "nutrition"],
  },

  // Bone Health
  {
    id: "MUSC015",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Have you had fractures or broken bones?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "once", label: "Once", score: 1 },
      { value: "2-3times", label: "2-3 times", score: 2 },
      { value: "4-5times", label: "4-5 times", score: 3 },
      { value: "many", label: "Many times", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["bone_density", "fracture_risk", "osteoporosis"],
  },
  {
    id: "MUSC016",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Have you been told you have osteoporosis or osteopenia?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "at_risk", label: "At risk", score: 2 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["bone_loss", "calcium", "vitamin_D"],
  },

  // Tendon & Ligament
  {
    id: "MUSC017",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have tendonitis or bursitis?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "recurrent", label: "Yes, recurrent", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["tendon_health", "repetitive_strain", "inflammation"],
  },
  {
    id: "MUSC018",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Are you hypermobile (double-jointed)?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "extremely", label: "Yes, extremely", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["hypermobility", "EDS", "connective_tissue"],
  },

  // Activity Level
  {
    id: "MUSC019",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Has pain limited your physical activities?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "severely", label: "Yes, severely", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["functional_limitation", "quality_of_life"],
  },
  {
    id: "MUSC020",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you avoid exercise due to pain or stiffness?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "completely", label: "Yes, completely avoid", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["exercise_avoidance", "deconditioning"],
  },

  // Specific Conditions
  {
    id: "MUSC021",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have restless leg syndrome?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "suspected", label: "Suspected", score: 1 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["RLS", "iron", "dopamine"],
  },
  {
    id: "MUSC022",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you grind your teeth or clench your jaw?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "nightly", label: "Every night", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["TMJ", "bruxism", "stress"],
  },

  // Posture
  {
    id: "MUSC023",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have poor posture?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very_poor", label: "Yes, very poor", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["posture", "spinal_alignment", "muscle_imbalance"],
  },
  {
    id: "MUSC024",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you sit for long periods daily?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "minimal", label: "Minimal sitting", score: 0 },
      { value: "2-4hours", label: "2-4 hours", score: 1 },
      { value: "5-8hours", label: "5-8 hours", score: 2 },
      { value: "9-12hours", label: "9-12 hours", score: 3 },
      { value: "over12", label: "Over 12 hours", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["sedentary", "hip_flexor", "back_pain"],
  },

  // Fibromyalgia Screening
  {
    id: "MUSC025",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have widespread body pain?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: [
      "fibromyalgia",
      "chronic_pain",
      "central_sensitization",
    ],
  },
  {
    id: "MUSC026",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Are you sensitive to touch or pressure?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "extremely", label: "Extremely sensitive", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["allodynia", "fibromyalgia", "nerve_sensitivity"],
  },

  // Recovery & Exercise
  {
    id: "MUSC027",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "How do you feel after exercise?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "energized", label: "Energized", score: 0 },
      { value: "good", label: "Good", score: 0 },
      { value: "tired", label: "Tired but good", score: 1 },
      { value: "exhausted", label: "Exhausted", score: 2 },
      { value: "worse", label: "Worse/More pain", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["exercise_recovery", "post_exertional_malaise"],
  },
  {
    id: "MUSC028",
    module: "SCREENING",
    bodySystem: BodySystems.MUSCULOSKELETAL,
    text: "Do you have delayed muscle soreness after exercise?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "none", label: "None", score: 0 },
      { value: "normal", label: "Normal (1-2 days)", score: 0 },
      { value: "prolonged", label: "Prolonged (3-4 days)", score: 2 },
      { value: "severe", label: "Severe (5+ days)", score: 3 },
      { value: "dont_exercise", label: "Don't exercise", score: 1 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["DOMS", "recovery_capacity", "inflammation"],
  },
];
