import { AssessmentQuestion } from "../../types";
import { BodySystems } from "../../body-systems";

export const respiratoryQuestions: AssessmentQuestion[] = [
  // Breathing Quality
  {
    id: "RESP001",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you experience shortness of breath at rest?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["respiratory_function", "cardiac_function", "anxiety"],
  },
  {
    id: "RESP002",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you have difficulty taking a deep breath?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["lung_capacity", "chest_tightness", "anxiety"],
  },
  {
    id: "RESP003",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you feel like you can't get enough air?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["air_hunger", "dyspnea", "hyperventilation"],
  },

  // Cough
  {
    id: "RESP004",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you have a chronic cough?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 1 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["chronic_cough", "GERD", "post_nasal_drip"],
  },
  {
    id: "RESP005",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Is your cough productive (bringing up phlegm)?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No/Dry cough", score: 0 },
      { value: "na", label: "No cough", score: 0 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["bronchitis", "infection", "COPD"],
    conditionalLogic: [
      {
        condition: "no",
        action: "skip",
        skipQuestions: ["RESP005", "RESP006"],
      },
    ],
  },
  {
    id: "RESP006",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "What color is the phlegm?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "clear", label: "Clear/White", score: 0 },
      { value: "yellow", label: "Yellow", score: 2 },
      { value: "green", label: "Green", score: 3 },
      { value: "brown", label: "Brown", score: 3 },
      { value: "blood", label: "Blood-tinged", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["infection", "inflammation", "bleeding"],
  },

  // Wheezing & Asthma
  {
    id: "RESP007",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you wheeze or hear whistling when breathing?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["asthma", "COPD", "airway_obstruction"],
  },
  {
    id: "RESP008",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Have you been diagnosed with asthma?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "childhood", label: "Yes, as a child only", score: 1 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["asthma", "airway_disease"],
  },
  {
    id: "RESP009",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you use an inhaler or nebulizer?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "no", label: "No", score: 0 },
      { value: "rarely", label: "Rarely/As needed", score: 1 },
      { value: "daily", label: "Daily", score: 2 },
      { value: "multiple", label: "Multiple times daily", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["asthma_control", "COPD", "medication_use"],
  },

  // Sinus & Upper Respiratory
  {
    id: "RESP010",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you have chronic sinus congestion?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "seasonal", label: "Seasonally", score: 1 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["sinusitis", "allergies", "immune_function"],
  },
  {
    id: "RESP011",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you have post-nasal drip?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["post_nasal_drip", "sinusitis", "allergies"],
  },
  {
    id: "RESP012",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you get frequent respiratory infections?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "never", label: "Never/Rarely", score: 0 },
      { value: "1-2year", label: "1-2 per year", score: 1 },
      { value: "3-4year", label: "3-4 per year", score: 2 },
      { value: "5-6year", label: "5-6 per year", score: 3 },
      { value: "monthly", label: "Monthly or more", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["immune_function", "respiratory_health"],
  },

  // Exercise & Activity
  {
    id: "RESP013",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you get winded easily with physical activity?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "very_easily", label: "Yes, very easily", score: 3 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: [
      "exercise_tolerance",
      "deconditioning",
      "lung_function",
    ],
  },
  {
    id: "RESP014",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you avoid exercise due to breathing problems?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["exercise_limitation", "quality_of_life"],
  },

  // Environmental Triggers
  {
    id: "RESP015",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Are your breathing symptoms worse with specific triggers?",
    type: "MULTIPLE_CHOICE",
    options: [
      { value: "none", label: "No triggers", score: 0 },
      { value: "dust", label: "Dust/Allergens", score: 2 },
      { value: "exercise", label: "Exercise", score: 2 },
      { value: "cold", label: "Cold air", score: 2 },
      { value: "multiple", label: "Multiple triggers", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["asthma_triggers", "allergies", "sensitivity"],
  },
  {
    id: "RESP016",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you react to perfumes, smoke, or chemical odors?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "severely", label: "Yes, severely", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["chemical_sensitivity", "MCS", "reactive_airway"],
  },

  // Sleep-Related Breathing
  {
    id: "RESP017",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you snore loudly?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "every_night", label: "Every night", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["sleep_apnea", "airway_obstruction"],
  },
  {
    id: "RESP018",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Have you been told you stop breathing during sleep?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 4 },
      { value: "no", label: "No", score: 0 },
      { value: "unsure", label: "Unsure/No partner", score: 1 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["sleep_apnea", "cardiovascular_risk"],
  },

  // Post-COVID Respiratory
  {
    id: "RESP019",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Since COVID-19, is your breathing worse?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "na", label: "Haven't had COVID", score: 0 },
    ],
    scoringWeight: 2.0,
    clinicalRelevance: ["post_covid_respiratory", "long_covid"],
  },
  {
    id: "RESP020",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you have a persistent cough since COVID-19?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "na", label: "Haven't had COVID", score: 0 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["post_covid_cough", "airway_inflammation"],
  },

  // Chest Symptoms
  {
    id: "RESP021",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you experience chest tightness when breathing?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["bronchospasm", "anxiety", "asthma"],
  },
  {
    id: "RESP022",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you have pain when taking a deep breath?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 3 },
      { value: "no", label: "No", score: 0 },
      { value: "sometimes", label: "Sometimes", score: 2 },
    ],
    scoringWeight: 1.5,
    clinicalRelevance: ["pleurisy", "costochondritis", "pneumonia"],
  },

  // Mucus Production
  {
    id: "RESP023",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you frequently clear your throat?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "constantly", label: "Constantly", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["mucus_production", "GERD", "post_nasal_drip"],
  },

  // Voice Changes
  {
    id: "RESP024",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Is your voice hoarse or raspy?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["laryngitis", "GERD", "vocal_strain"],
  },

  // Oxygen & Breathing Pattern
  {
    id: "RESP025",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you breathe through your mouth rather than nose?",
    type: "FREQUENCY",
    options: [
      { value: "never", label: "Never", score: 0 },
      { value: "rarely", label: "Rarely", score: 1 },
      { value: "sometimes", label: "Sometimes", score: 2 },
      { value: "often", label: "Often", score: 3 },
      { value: "always", label: "Always", score: 4 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["nasal_obstruction", "breathing_pattern", "dry_mouth"],
  },
  {
    id: "RESP026",
    module: "SCREENING",
    bodySystem: BodySystems.RESPIRATORY,
    text: "Do you yawn excessively or sigh frequently?",
    type: "YES_NO",
    options: [
      { value: "yes", label: "Yes", score: 2 },
      { value: "no", label: "No", score: 0 },
      { value: "constantly", label: "Yes, constantly", score: 3 },
    ],
    scoringWeight: 1.0,
    clinicalRelevance: ["air_hunger", "anxiety", "hyperventilation"],
  },
];
