"use client";

import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  MessageSquare,
  Target,
  Activity,
  Eye,
  AlertTriangle,
  Heart,
  Download,
  Copy,
} from "lucide-react";

interface CoachingNotes {
  keyHealthPriorities: string[];
  supplementRationale: string[];
  lifestyleRecommendations: string[];
  followUpMonitoring: string[];
  redFlagsToWatch: string[];
  motivationStrategies: string[];
}

interface CoachingNotesDisplayProps {
  clientId: string;
  clientName: string;
}

export function CoachingNotesDisplay({
  clientId,
  clientName,
}: CoachingNotesDisplayProps) {
  const [coachingNotes, setCoachingNotes] = useState<CoachingNotes | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  useEffect(() => {
    fetchCoachingNotes();
  }, [clientId]);

  const fetchCoachingNotes = async () => {
    try {
      const token = localStorage.getItem("token");
      const response = await fetch(`/api/clients/${clientId}/complete`, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (!response.ok) {
        throw new Error("Failed to fetch client data");
      }

      const data = await response.json();
      const client = data.client;
      const healthGoals = client.healthGoals || {};
      const analysisHistory = healthGoals.analysisHistory || [];

      // Find the most recent analysis with coaching notes
      const latestAnalysisWithNotes = analysisHistory.find(
        (analysis: any) => analysis.analysisData?.coachingNotes
      );

      if (latestAnalysisWithNotes) {
        setCoachingNotes(latestAnalysisWithNotes.analysisData.coachingNotes);
      }

    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  };

  const handleCopySection = async (sectionName: string, content: string[]) => {
    const text = `${sectionName}:\n${content
      .map((item) => `• ${item}`)
      .join("\n")}`;
    try {
      await navigator.clipboard.writeText(text);
      setCopiedSection(sectionName);
      setTimeout(() => setCopiedSection(null), 2000);
    } catch (err) {
      console.error("Failed to copy text:", err);
    }
  };

  const handleDownloadNotes = () => {
    if (!coachingNotes) return;

    const content = generateNotesContent();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${clientName.replace(/\s+/g, "-")}-Coaching-Notes.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateNotesContent = () => {
    if (!coachingNotes) return "";

    const sections = [
      {
        title: "Key Health Priorities",
        items: coachingNotes.keyHealthPriorities,
      },
      {
        title: "Supplement Rationale",
        items: coachingNotes.supplementRationale,
      },
      {
        title: "Lifestyle Recommendations",
        items: coachingNotes.lifestyleRecommendations,
      },
      {
        title: "Follow-Up Monitoring",
        items: coachingNotes.followUpMonitoring,
      },
      { title: "Red Flags to Watch", items: coachingNotes.redFlagsToWatch },
      {
        title: "Motivation Strategies",
        items: coachingNotes.motivationStrategies,
      },
    ];

    return `
COACHING NOTES
Client: ${clientName}
Date: ${new Date().toLocaleDateString()}

${sections
  .map(
    (section) =>
      `${section.title.toUpperCase()}:\n${(section.items || [])
        .map((item) => `• ${item}`)
        .join("\n")}`
  )
  .join("\n\n")}

---
Generated by FNTP Nutrition System
    `.trim();
  };

  if (loading) {
    return (
      <Card>
        <CardContent className="p-6">
          <div className="flex items-center justify-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600"></div>
            <span className="ml-3">Loading coaching notes...</span>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card>
        <CardContent className="p-6">
          <div className="text-red-600 flex items-center">
            <AlertTriangle className="w-5 h-5 mr-2" />
            Error loading coaching notes: {error}
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!coachingNotes) {
    return (
      <Card>
        <CardContent className="p-6">
          <div className="text-center py-8">
            <MessageSquare className="w-12 h-12 text-gray-400 mx-auto mb-3" />
            <p className="text-gray-600">No coaching notes found</p>
            <p className="text-sm text-gray-500">
              Import a Claude analysis to generate coaching notes
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <MessageSquare className="w-5 h-5" />
              Coaching Notes for {clientName}
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadNotes}
              className="flex items-center gap-2"
            >
              <Download className="w-4 h-4" />
              Download Notes
            </Button>
          </CardTitle>
        </CardHeader>
      </Card>

      {/* Notes Sections - Simplified to avoid dynamic icon issues */}
      <div className="grid gap-4">
        {/* Key Health Priorities */}
        <Card className="border-2 bg-red-50 border-red-200">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Target className="w-5 h-5" />
                Key Health Priorities
                <Badge className="bg-red-100 text-red-800">
                  {coachingNotes.keyHealthPriorities?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.keyHealthPriorities?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection("Key Health Priorities", coachingNotes.keyHealthPriorities || [])
                  }
                  className="h-8 px-2"
                >
                  {copiedSection === "Key Health Priorities" ? (
                    <span className="text-green-600 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.keyHealthPriorities?.length || 0) === 0 ? (
              <p className="text-gray-500 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.keyHealthPriorities || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-gray-400 mt-1 text-sm">•</span>
                    <span className="text-gray-700 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Supplement Rationale */}
        <Card className="border-2 bg-blue-50 border-blue-200">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Activity className="w-5 h-5" />
                Supplement Rationale
                <Badge className="bg-blue-100 text-blue-800">
                  {coachingNotes.supplementRationale?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.supplementRationale?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection("Supplement Rationale", coachingNotes.supplementRationale || [])
                  }
                  className="h-8 px-2"
                >
                  {copiedSection === "Supplement Rationale" ? (
                    <span className="text-green-600 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.supplementRationale?.length || 0) === 0 ? (
              <p className="text-gray-500 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.supplementRationale || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-gray-400 mt-1 text-sm">•</span>
                    <span className="text-gray-700 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Lifestyle Recommendations */}
        <Card className="border-2 bg-green-50 border-green-200">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Heart className="w-5 h-5" />
                Lifestyle Recommendations
                <Badge className="bg-green-100 text-green-800">
                  {coachingNotes.lifestyleRecommendations?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.lifestyleRecommendations?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection("Lifestyle Recommendations", coachingNotes.lifestyleRecommendations || [])
                  }
                  className="h-8 px-2"
                >
                  {copiedSection === "Lifestyle Recommendations" ? (
                    <span className="text-green-600 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.lifestyleRecommendations?.length || 0) === 0 ? (
              <p className="text-gray-500 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.lifestyleRecommendations || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-gray-400 mt-1 text-sm">•</span>
                    <span className="text-gray-700 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Follow-Up Monitoring */}
        <Card className="border-2 bg-purple-50 border-purple-200">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Eye className="w-5 h-5" />
                Follow-Up Monitoring
                <Badge className="bg-purple-100 text-purple-800">
                  {coachingNotes.followUpMonitoring?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.followUpMonitoring?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection("Follow-Up Monitoring", coachingNotes.followUpMonitoring || [])
                  }
                  className="h-8 px-2"
                >
                  {copiedSection === "Follow-Up Monitoring" ? (
                    <span className="text-green-600 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.followUpMonitoring?.length || 0) === 0 ? (
              <p className="text-gray-500 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.followUpMonitoring || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-gray-400 mt-1 text-sm">•</span>
                    <span className="text-gray-700 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Red Flags to Watch */}
        <Card className="border-2 bg-yellow-50 border-yellow-200">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <AlertTriangle className="w-5 h-5" />
                Red Flags to Watch
                <Badge className="bg-yellow-100 text-yellow-800">
                  {coachingNotes.redFlagsToWatch?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.redFlagsToWatch?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection("Red Flags to Watch", coachingNotes.redFlagsToWatch || [])
                  }
                  className="h-8 px-2"
                >
                  {copiedSection === "Red Flags to Watch" ? (
                    <span className="text-green-600 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.redFlagsToWatch?.length || 0) === 0 ? (
              <p className="text-gray-500 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.redFlagsToWatch || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-gray-400 mt-1 text-sm">•</span>
                    <span className="text-gray-700 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Motivation Strategies */}
        <Card className="border-2 bg-indigo-50 border-indigo-200">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <MessageSquare className="w-5 h-5" />
                Motivation Strategies
                <Badge className="bg-indigo-100 text-indigo-800">
                  {coachingNotes.motivationStrategies?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.motivationStrategies?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection("Motivation Strategies", coachingNotes.motivationStrategies || [])
                  }
                  className="h-8 px-2"
                >
                  {copiedSection === "Motivation Strategies" ? (
                    <span className="text-green-600 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.motivationStrategies?.length || 0) === 0 ? (
              <p className="text-gray-500 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.motivationStrategies || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-gray-400 mt-1 text-sm">•</span>
                    <span className="text-gray-700 leading-relaxed">{item}</span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}