"use client";

import React, { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  MessageSquare,
  Target,
  Activity,
  Eye,
  AlertTriangle,
  Heart,
  Download,
  Copy,
} from "lucide-react";

interface CoachingNotes {
  keyHealthPriorities: string[];
  supplementRationale: string[];
  lifestyleRecommendations: string[];
  followUpMonitoring: string[];
  redFlagsToWatch: string[];
  motivationStrategies: string[];
}

interface CoachingNotesDisplayProps {
  clientId: string;
  clientName: string;
}

export function CoachingNotesDisplay({
  clientId,
  clientName,
}: CoachingNotesDisplayProps) {
  const [coachingNotes, setCoachingNotes] = useState<CoachingNotes | null>(
    null
  );
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [copiedSection, setCopiedSection] = useState<string | null>(null);

  useEffect(() => {
    fetchCoachingNotes();
  }, [clientId]);

  const fetchCoachingNotes = async () => {
    try {
      const token = localStorage.getItem("token");
      const response = await fetch(`/api/clients/${clientId}/complete`, {
        headers: { Authorization: `Bearer ${token}` },
      });

      if (!response.ok) {
        throw new Error("Failed to fetch client data");
      }

      const data = await response.json();
      const client = data.client;
      const healthGoals = client.healthGoals || {};
      const analysisHistory = healthGoals.analysisHistory || [];

      // Find the most recent analysis with coaching notes
      const latestAnalysisWithNotes = analysisHistory.find(
        (analysis: any) => analysis.analysisData?.coachingNotes
      );

      if (latestAnalysisWithNotes) {
        setCoachingNotes(latestAnalysisWithNotes.analysisData.coachingNotes);
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Unknown error");
    } finally {
      setLoading(false);
    }
  };

  const handleCopySection = async (sectionName: string, content: string[]) => {
    const text = `${sectionName}:\n${content
      .map((item) => `• ${item}`)
      .join("\n")}`;
    try {
      await navigator.clipboard.writeText(text);
      setCopiedSection(sectionName);
      setTimeout(() => setCopiedSection(null), 2000);
    } catch (err) {
      console.error("Failed to copy text:", err);
    }
  };

  const handleDownloadNotes = () => {
    if (!coachingNotes) return;

    const content = generateNotesContent();
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${clientName.replace(/\s+/g, "-")}-Coaching-Notes.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const generateNotesContent = () => {
    if (!coachingNotes) return "";

    const sections = [
      {
        title: "Key Health Priorities",
        items: coachingNotes.keyHealthPriorities,
      },
      {
        title: "Supplement Rationale",
        items: coachingNotes.supplementRationale,
      },
      {
        title: "Lifestyle Recommendations",
        items: coachingNotes.lifestyleRecommendations,
      },
      {
        title: "Follow-Up Monitoring",
        items: coachingNotes.followUpMonitoring,
      },
      { title: "Red Flags to Watch", items: coachingNotes.redFlagsToWatch },
      {
        title: "Motivation Strategies",
        items: coachingNotes.motivationStrategies,
      },
    ];

    return `
COACHING NOTES
Client: ${clientName}
Date: ${new Date().toLocaleDateString()}

${sections
  .map(
    (section) =>
      `${section.title.toUpperCase()}:\n${(section.items || [])
        .map((item) => `• ${item}`)
        .join("\n")}`
  )
  .join("\n\n")}

---
Generated by FNTP Nutrition System
    `.trim();
  };

  if (loading) {
    return (
      <Card className="bg-gray-800 border-gray-700">
        <CardContent className="p-6">
          <div className="flex items-center justify-center">
            <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-400"></div>
            <span className="ml-3 text-gray-300">Loading coaching notes...</span>
          </div>
        </CardContent>
      </Card>
    );
  }

  if (error) {
    return (
      <Card className="bg-gray-800 border-gray-700">
        <CardContent className="p-6">
          <div className="text-red-400 flex items-center">
            <AlertTriangle className="w-5 h-5 mr-2" />
            Error loading coaching notes: {error}
          </div>
        </CardContent>
      </Card>
    );
  }

  if (!coachingNotes) {
    return (
      <Card className="bg-gray-800 border-gray-700">
        <CardContent className="p-6">
          <div className="text-center py-8">
            <MessageSquare className="w-12 h-12 text-gray-400 mx-auto mb-3" />
            <p className="text-gray-300">No coaching notes found</p>
            <p className="text-sm text-gray-400">
              Import a Claude analysis to generate coaching notes
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <Card className="bg-gray-800 border-gray-700">
        <CardHeader>
          <CardTitle className="flex items-center justify-between text-white">
            <div className="flex items-center gap-2">
              <MessageSquare className="w-5 h-5" />
              Coaching Notes for {clientName}
            </div>
            <Button
              variant="outline"
              size="sm"
              onClick={handleDownloadNotes}
              className="flex items-center gap-2 border-gray-600 text-gray-300 hover:bg-gray-700 hover:text-white"
            >
              <Download className="w-4 h-4" />
              Download Notes
            </Button>
          </CardTitle>
        </CardHeader>
      </Card>

      {/* Notes Sections - Dark theme with color-coded sections */}
      <div className="grid gap-4">
        {/* Key Health Priorities */}
        <Card className="border-2 bg-gray-800 border-red-500/30">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Target className="w-5 h-5 text-red-400" />
                <span className="text-white">Key Health Priorities</span>
                <Badge className="bg-red-900/30 border border-red-500/50 text-red-300">
                  {coachingNotes.keyHealthPriorities?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.keyHealthPriorities?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection(
                      "Key Health Priorities",
                      coachingNotes.keyHealthPriorities || []
                    )
                  }
                  className="h-8 px-2 text-gray-300 hover:text-white hover:bg-gray-700"
                >
                  {copiedSection === "Key Health Priorities" ? (
                    <span className="text-green-400 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.keyHealthPriorities?.length || 0) === 0 ? (
              <p className="text-gray-400 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.keyHealthPriorities || []).map(
                  (item, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="text-red-400 mt-1 text-sm">•</span>
                      <span className="text-gray-300 leading-relaxed">
                        {item}
                      </span>
                    </li>
                  )
                )}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Supplement Rationale */}
        <Card className="border-2 bg-gray-800 border-blue-500/30">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Activity className="w-5 h-5 text-blue-400" />
                <span className="text-white">Supplement Rationale</span>
                <Badge className="bg-blue-900/30 border border-blue-500/50 text-blue-300">
                  {coachingNotes.supplementRationale?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.supplementRationale?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection(
                      "Supplement Rationale",
                      coachingNotes.supplementRationale || []
                    )
                  }
                  className="h-8 px-2 text-gray-300 hover:text-white hover:bg-gray-700"
                >
                  {copiedSection === "Supplement Rationale" ? (
                    <span className="text-green-400 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.supplementRationale?.length || 0) === 0 ? (
              <p className="text-gray-400 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.supplementRationale || []).map(
                  (item, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="text-blue-400 mt-1 text-sm">•</span>
                      <span className="text-gray-300 leading-relaxed">
                        {item}
                      </span>
                    </li>
                  )
                )}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Lifestyle Recommendations */}
        <Card className="border-2 bg-gray-800 border-green-500/30">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Heart className="w-5 h-5 text-green-400" />
                <span className="text-white">Lifestyle Recommendations</span>
                <Badge className="bg-green-900/30 border border-green-500/50 text-green-300">
                  {coachingNotes.lifestyleRecommendations?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.lifestyleRecommendations?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection(
                      "Lifestyle Recommendations",
                      coachingNotes.lifestyleRecommendations || []
                    )
                  }
                  className="h-8 px-2 text-gray-300 hover:text-white hover:bg-gray-700"
                >
                  {copiedSection === "Lifestyle Recommendations" ? (
                    <span className="text-green-400 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.lifestyleRecommendations?.length || 0) === 0 ? (
              <p className="text-gray-400 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.lifestyleRecommendations || []).map(
                  (item, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="text-green-400 mt-1 text-sm">•</span>
                      <span className="text-gray-300 leading-relaxed">
                        {item}
                      </span>
                    </li>
                  )
                )}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Follow-Up Monitoring */}
        <Card className="border-2 bg-gray-800 border-purple-500/30">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <Eye className="w-5 h-5 text-purple-400" />
                <span className="text-white">Follow-Up Monitoring</span>
                <Badge className="bg-purple-900/30 border border-purple-500/50 text-purple-300">
                  {coachingNotes.followUpMonitoring?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.followUpMonitoring?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection(
                      "Follow-Up Monitoring",
                      coachingNotes.followUpMonitoring || []
                    )
                  }
                  className="h-8 px-2 text-gray-300 hover:text-white hover:bg-gray-700"
                >
                  {copiedSection === "Follow-Up Monitoring" ? (
                    <span className="text-green-400 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.followUpMonitoring?.length || 0) === 0 ? (
              <p className="text-gray-400 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.followUpMonitoring || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-purple-400 mt-1 text-sm">•</span>
                    <span className="text-gray-300 leading-relaxed">
                      {item}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Red Flags to Watch */}
        <Card className="border-2 bg-gray-800 border-yellow-500/30">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <AlertTriangle className="w-5 h-5 text-yellow-400" />
                <span className="text-white">Red Flags to Watch</span>
                <Badge className="bg-yellow-900/30 border border-yellow-500/50 text-yellow-300">
                  {coachingNotes.redFlagsToWatch?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.redFlagsToWatch?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection(
                      "Red Flags to Watch",
                      coachingNotes.redFlagsToWatch || []
                    )
                  }
                  className="h-8 px-2 text-gray-300 hover:text-white hover:bg-gray-700"
                >
                  {copiedSection === "Red Flags to Watch" ? (
                    <span className="text-green-400 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.redFlagsToWatch?.length || 0) === 0 ? (
              <p className="text-gray-400 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.redFlagsToWatch || []).map((item, index) => (
                  <li key={index} className="flex items-start gap-2">
                    <span className="text-yellow-400 mt-1 text-sm">•</span>
                    <span className="text-gray-300 leading-relaxed">
                      {item}
                    </span>
                  </li>
                ))}
              </ul>
            )}
          </CardContent>
        </Card>

        {/* Motivation Strategies */}
        <Card className="border-2 bg-gray-800 border-indigo-500/30">
          <CardHeader className="pb-3">
            <CardTitle className="flex items-center justify-between text-lg">
              <div className="flex items-center gap-2">
                <MessageSquare className="w-5 h-5 text-indigo-400" />
                <span className="text-white">Motivation Strategies</span>
                <Badge className="bg-indigo-900/30 border border-indigo-500/50 text-indigo-300">
                  {coachingNotes.motivationStrategies?.length || 0}
                </Badge>
              </div>
              {(coachingNotes.motivationStrategies?.length || 0) > 0 && (
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    handleCopySection(
                      "Motivation Strategies",
                      coachingNotes.motivationStrategies || []
                    )
                  }
                  className="h-8 px-2 text-gray-300 hover:text-white hover:bg-gray-700"
                >
                  {copiedSection === "Motivation Strategies" ? (
                    <span className="text-green-400 text-xs">Copied!</span>
                  ) : (
                    <Copy className="w-4 h-4" />
                  )}
                </Button>
              )}
            </CardTitle>
          </CardHeader>
          <CardContent>
            {(coachingNotes.motivationStrategies?.length || 0) === 0 ? (
              <p className="text-gray-400 italic">No items in this section</p>
            ) : (
              <ul className="space-y-2">
                {(coachingNotes.motivationStrategies || []).map(
                  (item, index) => (
                    <li key={index} className="flex items-start gap-2">
                      <span className="text-indigo-400 mt-1 text-sm">•</span>
                      <span className="text-gray-300 leading-relaxed">
                        {item}
                      </span>
                    </li>
                  )
                )}
              </ul>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
