import { promises as fs } from 'fs';
import * as path from 'path';
import { S3Client, GetObjectCommand } from '@aws-sdk/client-s3';

interface Document {
  id: string;
  fileName: string;
  originalFileName?: string;
  fileUrl?: string;
  documentType: string;
  uploadedAt: Date;
  status: string;
  fileSize: number;
}

interface Assessment {
  id: string;
  status: string;
  completedAt: Date | null;
  responses: AssessmentResponse[];
}

interface AssessmentResponse {
  questionId: number;
  questionText: string;
  category: string;
  score: number;
  answeredAt: Date;
}

/**
 * Generate comprehensive timeline analysis for client
 */
export async function generateTimelineAnalysis(client: any): Promise<string> {
  const healthEvents = [];

  // Add assessment events
  if (client.simpleAssessments) {
    for (const assessment of client.simpleAssessments) {
      if (assessment.completedAt) {
        healthEvents.push({
          date: assessment.completedAt,
          type: 'Assessment',
          event: `Functional Medicine Assessment Completed (${assessment.responses?.length || 0} questions)`,
          details: assessment.responses
            ? generateAssessmentSummary(assessment.responses)
            : 'Assessment data not available',
        });
      }
    }
  }

  // Add document events
  if (client.documents) {
    for (const document of client.documents) {
      healthEvents.push({
        date: document.uploadedAt,
        type: 'Document',
        event: `${document.documentType} uploaded: ${document.originalFileName || document.fileName}`,
        details: `File size: ${Math.round(document.fileSize / 1024)}KB, Status: ${document.status}`,
      });
    }
  }

  // Add protocol events
  if (client.protocols) {
    for (const protocol of client.protocols) {
      healthEvents.push({
        date: protocol.createdAt,
        type: 'Protocol',
        event: `Protocol Started: ${protocol.protocolName}`,
        details: `Status: ${protocol.status}, Supplements: ${Object.keys(protocol.supplements || {}).length}`,
      });
    }
  }

  // Add clinical note events
  if (client.notes) {
    for (const note of client.notes) {
      healthEvents.push({
        date: note.createdAt,
        type: 'Clinical Note',
        event: `${note.noteType} Session: ${note.title || 'Session Notes'}`,
        details:
          note.chiefComplaints || note.generalNotes || 'Clinical documentation',
      });
    }
  }

  // Sort events chronologically
  healthEvents.sort(
    (a, b) => new Date(a.date).getTime() - new Date(b.date).getTime()
  );

  return `# ${client.firstName} ${client.lastName} - Health Timeline Analysis

## 👤 Client Overview
- **Name**: ${client.firstName} ${client.lastName}
- **Email**: ${client.email}
- **Date of Birth**: ${client.dateOfBirth || 'Not specified'}
- **Gender**: ${client.gender || 'Not specified'}
- **Truck Driver**: ${client.isTruckDriver ? 'Yes' : 'No'}
- **Export Date**: ${new Date().toLocaleDateString()}

## 🏥 Health Goals
${client.healthGoals ? JSON.stringify(client.healthGoals, null, 2) : 'No health goals specified'}

## 💊 Current Medications
${client.medications ? JSON.stringify(client.medications, null, 2) : 'No medications listed'}

## 🩺 Medical Conditions
${client.conditions ? JSON.stringify(client.conditions, null, 2) : 'No conditions listed'}

## ⚠️ Allergies
${client.allergies ? JSON.stringify(client.allergies, null, 2) : 'No allergies listed'}

## 📅 Chronological Health Journey

${healthEvents
  .map(
    (event, index) => `
### ${index + 1}. ${event.event}
**Date**: ${new Date(event.date).toLocaleDateString()}  
**Type**: ${event.type}  
**Details**: ${event.details}
`
  )
  .join('\n')}

## 📊 Data Summary
- **Total Health Events**: ${healthEvents.length}
- **Assessments Completed**: ${client.simpleAssessments?.length || 0}
- **Documents Uploaded**: ${client.documents?.length || 0}
- **Active Protocols**: ${client.protocols?.filter((p: any) => p.status === 'active').length || 0}
- **Clinical Notes**: ${client.notes?.length || 0}

## 🎯 Assessment Performance Overview
${generateAssessmentOverview(client.simpleAssessments)}

## 📋 Protocol History
${generateProtocolSummary(client.protocols)}

---
*Generated by FNTP Comprehensive Export System on ${new Date().toISOString()}*
*This timeline provides chronological context for Claude Desktop protocol development*
`;
}

/**
 * Generate functional medicine assessment analysis
 */
export async function generateAssessmentAnalysis(
  assessments: Assessment[]
): Promise<string> {
  if (!assessments.length) {
    return `# Functional Medicine Assessment Analysis

## 📊 Assessment Status
No assessments have been completed for this client.

## 🎯 Recommendations
1. Complete the 80-question functional medicine assessment
2. Review health goals and concerns
3. Upload any relevant medical documents

---
*No assessment data available for analysis*
`;
  }

  const latestAssessment = assessments[0];
  const responses = latestAssessment.responses || [];

  // Analyze responses by category
  const categoryAnalysis = analyzeCategoryResponses(responses);
  const highestScores = responses
    .filter(r => r.score >= 4)
    .sort((a, b) => b.score - a.score)
    .slice(0, 10);

  const averageScore =
    responses.length > 0
      ? responses.reduce((sum, r) => sum + r.score, 0) / responses.length
      : 0;

  return `# Functional Medicine Assessment Analysis

## 📊 Assessment Overview
- **Assessment Date**: ${latestAssessment.completedAt?.toLocaleDateString() || 'In Progress'}
- **Questions Completed**: ${responses.length}/80
- **Completion Status**: ${latestAssessment.status}
- **Average Score**: ${averageScore.toFixed(1)}/5.0
- **High Priority Issues**: ${highestScores.length} (scores 4-5)

## 🎯 Category Analysis
${Object.entries(categoryAnalysis)
  .map(
    ([category, data]: [string, any]) => `
### ${category.toUpperCase()}
- **Average Score**: ${data.averageScore}/5.0
- **Question Count**: ${data.questionCount}
- **High Priority**: ${data.highPriorityCount} questions (score 4+)
- **Critical Concerns**: ${data.criticalCount} questions (score 5)
`
  )
  .join('')}

## 🚨 High Priority Findings (Score 4-5)
${
  highestScores.length > 0
    ? highestScores
        .map(
          (response, index) => `
${index + 1}. **${response.questionText}** (Score: ${response.score}/5)
   - Category: ${response.category}
   - Date: ${response.answeredAt.toLocaleDateString()}
`
        )
        .join('')
    : 'No high priority findings identified'
}

## 📈 Assessment Trends
${generateAssessmentTrends(assessments)}

## 🎯 Recommendations for Protocol Development
Based on the assessment patterns, the following areas require attention:

${generateProtocolRecommendations(categoryAnalysis, highestScores)}

---
*This analysis provides structured assessment data for Claude Desktop protocol development*
*Use this data alongside raw documents for comprehensive health analysis*
`;
}

/**
 * Generate export guide for Claude Desktop usage
 */
export function generateExportGuide(client: any, options: any): string {
  const documentsInfo =
    client.documents
      ?.map(
        (doc: Document) =>
          `- **${doc.originalFileName || doc.fileName}**: ${doc.documentType} (${Math.round(doc.fileSize / 1024)}KB)`
      )
      .join('\n') || 'No documents available';

  return `# Export Package Guide - ${client.firstName} ${client.lastName}

## 📦 Package Contents
This comprehensive export contains all client data needed for Claude Desktop analysis:

### 📊 Structured Analysis Files
- **Timeline Analysis**: Complete chronological health journey
- **Assessment Analysis**: Functional medicine assessment results and patterns  
- **Client Data (JSON)**: All structured data for cross-referencing
- **Export Guide**: This usage instruction file

### 📁 Raw Documents Folder
${documentsInfo}

## 🎯 Usage Instructions for Claude Desktop

### Step 1: Upload Complete Package
Upload this entire ZIP file to Claude Desktop, or extract and upload individual files based on your analysis needs.

### Step 2: Start Analysis
Use this recommended prompt structure:

\`\`\`
I am a functional medicine practitioner analyzing a comprehensive client package. 

This package includes:
- Structured timeline analysis with chronological health events
- Functional medicine assessment results (80-question assessment)
- Raw documents including NutriQ reports, NAQ questionnaires, lab results
- Previous protocol history and clinical notes
- Complete client health profile

Please provide:
1. **Comprehensive Health Analysis**: Pattern recognition across all data sources
2. **Root Cause Analysis**: Primary dysfunction patterns and connections
3. **Prioritized Treatment Protocol**: 3-phase intervention plan
4. **Supplement Recommendations**: Specific products, dosages, and timing
5. **Monitoring Plan**: Follow-up testing and progress tracking
6. **Risk Assessment**: Contraindications and safety considerations

Focus on functional medicine approaches that address root causes rather than symptom management.
\`\`\`

### Step 3: Document Processing Priority
1. **Start with structured files** (timeline and assessment analysis) for context
2. **Analyze raw documents** (NutriQ, NAQ, lab reports) for detailed data extraction
3. **Cross-reference findings** between structured analysis and document content
4. **Generate comprehensive protocols** based on all available data

## 🏥 Client Context for Analysis

### Health Profile
- **Primary Health Goals**: ${client.healthGoals ? JSON.stringify(client.healthGoals) : 'General health optimization'}
- **Current Medications**: ${client.medications ? 'See data file for details' : 'None listed'}
- **Known Conditions**: ${client.conditions ? 'See data file for details' : 'None listed'}
- **Allergies**: ${client.allergies ? 'See data file for details' : 'None listed'}

### Assessment Status
- **Assessments Completed**: ${client.simpleAssessments?.length || 0}
- **Latest Assessment**: ${
    client.simpleAssessments?.[0]?.completedAt
      ? new Date(client.simpleAssessments[0].completedAt).toLocaleDateString()
      : 'None completed'
  }

### Available Documents
- **Document Count**: ${client.documents?.length || 0}
- **Document Types**: ${
    client.documents
      ?.map((d: Document) => d.documentType)
      .filter((v: string, i: number, a: string[]) => a.indexOf(v) === i)
      .join(', ') || 'None'
  }

### Protocol History
- **Previous Protocols**: ${client.protocols?.length || 0}
- **Current Status**: ${client.protocols?.find((p: any) => p.status === 'active') ? 'Active protocol in progress' : 'No active protocols'}

## ⚡ Expected Claude Desktop Capabilities

This export enables Claude Desktop to:

✅ **Document Analysis**: Direct reading of NutriQ reports, NAQ questionnaires, lab results  
✅ **Pattern Recognition**: Cross-referencing symptoms across multiple data sources  
✅ **Protocol Development**: Evidence-based treatment plans with specific recommendations  
✅ **Risk Assessment**: Safety considerations based on complete health picture  
✅ **Root Cause Analysis**: Identifying underlying dysfunctions driving symptoms  
✅ **Monitoring Plans**: Follow-up testing and progress tracking strategies  

## 📞 Technical Notes
- **Export Format**: ZIP package optimized for AI analysis
- **File Structure**: Organized for sequential Claude Desktop processing
- **Data Integrity**: All timestamps preserved for chronological analysis
- **Document Access**: Raw files included for direct Claude analysis

---
*Export Generated*: ${new Date().toISOString()}  
*Export Type*: Comprehensive Clinical Package  
*Intended Use*: Claude Desktop Protocol Development  
*System*: FNTP Nutrition Practice Management
`;
}

/**
 * Fetch document content from storage
 */
export async function fetchDocumentContent(
  document: Document
): Promise<Buffer | null> {
  try {
    // Handle S3 URLs
    if (document.fileUrl && document.fileUrl.includes('amazonaws.com')) {
      // For S3 URLs, we would need to use S3 client
      // For now, return null as we may not have proper S3 access
      return null;
    }

    // Handle local file storage
    if (document.fileUrl && document.fileUrl.startsWith('/')) {
      try {
        const filePath = path.join(process.cwd(), 'uploads', document.fileName);
        const buffer = await fs.readFile(filePath);
        return buffer;
      } catch (error) {
        console.error(`Local file not found: ${document.fileName}`);
        return null;
      }
    }

    // Handle HTTP URLs
    if (document.fileUrl && document.fileUrl.startsWith('http')) {
      const response = await fetch(document.fileUrl);
      if (response.ok) {
        return Buffer.from(await response.arrayBuffer());
      }
    }

    return null;
  } catch (error) {
    console.error('Error fetching document:', error);
    return null;
  }
}

/**
 * Analyze responses by category for pattern recognition
 */
function analyzeCategoryResponses(responses: AssessmentResponse[]) {
  const categories: Record<
    string,
    {
      scores: number[];
      averageScore: number;
      questionCount: number;
      highPriorityCount: number;
      criticalCount: number;
    }
  > = {};

  for (const response of responses) {
    const category = response.category || 'uncategorized';

    if (!categories[category]) {
      categories[category] = {
        scores: [],
        averageScore: 0,
        questionCount: 0,
        highPriorityCount: 0,
        criticalCount: 0,
      };
    }

    categories[category].scores.push(response.score);
    categories[category].questionCount++;
    if (response.score >= 4) categories[category].highPriorityCount++;
    if (response.score === 5) categories[category].criticalCount++;
  }

  // Calculate averages
  Object.values(categories).forEach(category => {
    category.averageScore =
      category.scores.length > 0
        ? Number(
            (
              category.scores.reduce((sum, score) => sum + score, 0) /
              category.scores.length
            ).toFixed(1)
          )
        : 0;
  });

  return categories;
}

/**
 * Generate assessment summary for timeline
 */
function generateAssessmentSummary(responses: AssessmentResponse[]): string {
  const averageScore =
    responses.reduce((sum, r) => sum + r.score, 0) / responses.length;
  const highPriorityCount = responses.filter(r => r.score >= 4).length;

  return `Average score: ${averageScore.toFixed(1)}/5.0, High priority issues: ${highPriorityCount}`;
}

/**
 * Generate assessment overview for timeline
 */
function generateAssessmentOverview(assessments: Assessment[]): string {
  if (!assessments || assessments.length === 0) {
    return 'No assessments completed';
  }

  const latest = assessments[0];
  const averageScore =
    latest.responses?.length > 0
      ? latest.responses.reduce((sum, r) => sum + r.score, 0) /
        latest.responses.length
      : 0;

  return `
### Latest Assessment (${latest.completedAt?.toLocaleDateString()})
- **Questions Answered**: ${latest.responses?.length || 0}/80
- **Average Health Score**: ${averageScore.toFixed(1)}/5.0
- **Status**: ${latest.status}
- **High Priority Issues**: ${latest.responses?.filter(r => r.score >= 4).length || 0}
`;
}

/**
 * Generate protocol summary
 */
function generateProtocolSummary(protocols: any[]): string {
  if (!protocols || protocols.length === 0) {
    return 'No protocols have been implemented';
  }

  return protocols
    .map(
      (protocol, index) => `
### ${index + 1}. ${protocol.protocolName}
- **Status**: ${protocol.status}
- **Created**: ${protocol.createdAt ? new Date(protocol.createdAt).toLocaleDateString() : 'Date unknown'}
- **Supplements**: ${Object.keys(protocol.supplements || {}).length} items
- **Dietary Guidelines**: ${protocol.dietary ? 'Included' : 'Not specified'}
- **Lifestyle Modifications**: ${protocol.lifestyle ? 'Included' : 'Not specified'}
`
    )
    .join('\n');
}

/**
 * Generate assessment trends analysis
 */
function generateAssessmentTrends(assessments: Assessment[]): string {
  if (assessments.length < 2) {
    return 'Insufficient data for trend analysis (need multiple assessments)';
  }

  const latest = assessments[0];
  const previous = assessments[1];

  if (!latest.responses || !previous.responses) {
    return 'Assessment data incomplete for trend analysis';
  }

  const latestAvg =
    latest.responses.reduce((sum, r) => sum + r.score, 0) /
    latest.responses.length;
  const previousAvg =
    previous.responses.reduce((sum, r) => sum + r.score, 0) /
    previous.responses.length;

  const change = latestAvg - previousAvg;
  const trend =
    change > 0.2 ? 'Worsening' : change < -0.2 ? 'Improving' : 'Stable';

  return `
### Trend Analysis (Last 2 Assessments)
- **Latest Average**: ${latestAvg.toFixed(1)}/5.0
- **Previous Average**: ${previousAvg.toFixed(1)}/5.0
- **Change**: ${change > 0 ? '+' : ''}${change.toFixed(1)}
- **Overall Trend**: ${trend}
`;
}

/**
 * Generate protocol recommendations based on assessment patterns
 */
function generateProtocolRecommendations(
  categoryAnalysis: any,
  highScores: AssessmentResponse[]
): string {
  const priorityCategories = Object.entries(categoryAnalysis)
    .filter(([_, data]: [string, any]) => data.averageScore >= 3.0)
    .sort((a, b) => (b[1] as any).averageScore - (a[1] as any).averageScore)
    .slice(0, 5);

  if (priorityCategories.length === 0) {
    return `
### Health Optimization Focus
- Overall assessment scores are in healthy range
- Focus on preventive care and optimization protocols
- Consider advanced functional testing for deeper insights
`;
  }

  return `
### Priority Treatment Areas
${priorityCategories
  .map(
    ([category, data]: [string, any]) => `
**${category.toUpperCase()}** (Score: ${data.averageScore}/5.0)
- ${data.questionCount} questions assessed
- ${data.highPriorityCount} high priority concerns
- ${data.criticalCount} critical issues
`
  )
  .join('')}

### Immediate Intervention Recommendations
${highScores
  .slice(0, 5)
  .map(
    (response, index) => `
${index + 1}. **${response.category}**: ${response.questionText} (${response.score}/5)
   - Requires targeted functional medicine intervention
   - Consider testing and targeted supplementation
`
  )
  .join('')}

### Protocol Development Priority
1. **Address Critical Findings**: Focus on scores of 5/5 first
2. **System-Based Approach**: Target highest-scoring categories
3. **Root Cause Investigation**: Look for underlying patterns
4. **Monitoring Plan**: Track improvements in high-priority areas
`;
}
