/**
 * Ultimate Functional Medicine Digestive Assessment Questions
 * 
 * Comprehensive 45+ question system exceeding NutriQ capabilities
 * with modern FM insights including EMF sensitivity, seed oil inflammation,
 * mold/biotoxin assessment, and sophisticated root cause analysis.
 */

export interface DigestiveQuestion {
  id: number;
  category: 'upper_gi' | 'small_intestine' | 'large_intestine' | 'liver_detox' | 'modern_factors';
  subcategory: string;
  questionText: string;
  questionContext?: string;
  clinicalSignificance: string;
  scaleType: 'frequency' | 'severity' | 'yes_no' | 'quantity';
  reverseScoring?: boolean;
  diagnosticWeight: number; // 0.5-3.0 based on clinical importance
  symptomType: 'root_cause' | 'primary_symptom' | 'secondary_symptom' | 'modifier';
  conditionAssociations: string[];
  isTraditional: boolean;
  isModernInsight: boolean;
  environmentalFactor?: string;
  displayOrder: number;
  requiredLevel: 'required' | 'standard' | 'optional';
}

export const DIGESTIVE_QUESTIONS: DigestiveQuestion[] = [
  // ====== UPPER GI FUNCTION (12 QUESTIONS) ======
  {
    id: 1,
    category: 'upper_gi',
    subcategory: 'stomach_acid_production',
    questionText: 'How often do you experience belching, gas, or bloating within 30 minutes of eating?',
    questionContext: 'This occurs immediately after eating, not hours later',
    clinicalSignificance: 'Primary indicator of hypochlorhydria (low stomach acid) - fundamental to all digestion',
    scaleType: 'frequency',
    diagnosticWeight: 2.8,
    symptomType: 'root_cause',
    conditionAssociations: ['hypochlorhydria', 'SIBO', 'malabsorption'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 1,
    requiredLevel: 'required'
  },
  {
    id: 2,
    category: 'upper_gi',
    subcategory: 'stomach_acid_production',
    questionText: 'How often do you feel excessively full after normal-sized meals?',
    questionContext: 'Feeling like food just sits in your stomach',
    clinicalSignificance: 'Indicates gastroparesis or severe hypochlorhydria affecting gastric emptying',
    scaleType: 'frequency',
    diagnosticWeight: 2.5,
    symptomType: 'primary_symptom',
    conditionAssociations: ['gastroparesis', 'hypochlorhydria', 'vagal_dysfunction'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 2,
    requiredLevel: 'required'
  },
  {
    id: 3,
    category: 'upper_gi',
    subcategory: 'stomach_acid_production',
    questionText: 'How often do you experience heartburn or acid reflux symptoms?',
    questionContext: 'Burning sensation in chest, throat, or regurgitation',
    clinicalSignificance: 'Paradoxically often indicates LOW stomach acid, not high - critical diagnostic distinction',
    scaleType: 'frequency',
    diagnosticWeight: 2.2,
    symptomType: 'primary_symptom',
    conditionAssociations: ['hypochlorhydria', 'hiatal_hernia', 'SIBO'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 3,
    requiredLevel: 'required'
  },
  {
    id: 4,
    category: 'upper_gi',
    subcategory: 'enzyme_function',
    questionText: 'How completely does your body appear to digest food?',
    questionContext: 'Based on what you observe in stools. 0=Completely digested, 5=Frequently see undigested food pieces.',
    clinicalSignificance: 'Direct indicator of pancreatic enzyme insufficiency or severe hypochlorhydria',
    scaleType: 'frequency',
    diagnosticWeight: 2.9,
    symptomType: 'root_cause',
    conditionAssociations: ['pancreatic_insufficiency', 'hypochlorhydria', 'malabsorption'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 4,
    requiredLevel: 'required'
  },
  {
    id: 5,
    category: 'upper_gi',
    subcategory: 'enzyme_function',
    questionText: 'How often do you experience stomach upset when taking vitamins or supplements?',
    questionContext: 'Nausea, cramping, or discomfort specifically from supplements',
    clinicalSignificance: 'Indicates inadequate stomach acid for mineral absorption and supplement breakdown',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    symptomType: 'primary_symptom',
    conditionAssociations: ['hypochlorhydria', 'mineral_malabsorption'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 5,
    requiredLevel: 'standard'
  },
  {
    id: 6,
    category: 'upper_gi',
    subcategory: 'enzyme_function',
    questionText: 'How often do you lose your appetite for protein/meat?',
    questionContext: 'Decreased desire for or aversion to protein-rich foods',
    clinicalSignificance: 'Classic sign of protein maldigestion due to low HCl and pepsin production',
    scaleType: 'frequency',
    diagnosticWeight: 2.6,
    symptomType: 'primary_symptom',
    conditionAssociations: ['hypochlorhydria', 'protein_maldigestion', 'B12_deficiency'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 6,
    requiredLevel: 'standard'
  },
  {
    id: 7,
    category: 'upper_gi',
    subcategory: 'emf_stress_impact',
    questionText: 'How does using electronic devices during meals affect your digestion?',
    questionContext: 'Multitasking during meals with digital devices',
    clinicalSignificance: 'EMF exposure during eating disrupts vagal nerve function and digestive enzyme production',
    scaleType: 'frequency',
    diagnosticWeight: 1.8,
    symptomType: 'modifier',
    conditionAssociations: ['vagal_dysfunction', 'emf_sensitivity', 'stress_digestion'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'emf',
    displayOrder: 7,
    requiredLevel: 'standard'
  },
  {
    id: 8,
    category: 'upper_gi',
    subcategory: 'emf_stress_impact',
    questionText: 'How often do you experience digestive symptoms that worsen during high-stress periods?',
    questionContext: 'Digestive problems increase during work deadlines, life changes, or emotional stress',
    clinicalSignificance: 'HPA axis dysfunction directly impairs digestive function through cortisol and autonomic disruption',
    scaleType: 'frequency',
    diagnosticWeight: 2.1,
    symptomType: 'modifier',
    conditionAssociations: ['adrenal_dysfunction', 'vagal_dysfunction', 'cortisol_dysregulation'],
    isTraditional: true,
    isModernInsight: false,
    environmentalFactor: 'stress',
    displayOrder: 8,
    requiredLevel: 'standard'
  },
  {
    id: 9,
    category: 'upper_gi',
    subcategory: 'emf_stress_impact',
    questionText: 'How often do you eat meals in environments with WiFi, cell towers, or high EMF exposure?',
    questionContext: 'Restaurants, offices, or areas with multiple wireless devices',
    clinicalSignificance: 'Modern insight: EMF exposure during meals disrupts cellular energy production needed for digestion',
    scaleType: 'frequency',
    diagnosticWeight: 1.6,
    symptomType: 'modifier',
    conditionAssociations: ['emf_sensitivity', 'mitochondrial_dysfunction', 'cellular_stress'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'emf',
    displayOrder: 9,
    requiredLevel: 'optional'
  },
  {
    id: 10,
    category: 'upper_gi',
    subcategory: 'circadian_timing',
    questionText: 'How often do you feel like skipping breakfast or have no morning appetite?',
    questionContext: 'Lack of hunger or desire for food in the first 2 hours after waking',
    clinicalSignificance: 'Indicates circadian disruption affecting natural cortisol rhythm and digestive enzyme cycling',
    scaleType: 'frequency',
    diagnosticWeight: 2.0,
    symptomType: 'modifier',
    conditionAssociations: ['circadian_disruption', 'adrenal_dysfunction', 'cortisol_dysregulation'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'circadian',
    displayOrder: 10,
    requiredLevel: 'standard'
  },
  {
    id: 11,
    category: 'upper_gi',
    subcategory: 'circadian_timing',
    questionText: 'How does your evening meal timing affect your digestion?',
    questionContext: 'Digestive symptoms increase with meals after 8 PM',
    clinicalSignificance: 'Natural digestive enzyme production decreases at night; late eating disrupts circadian metabolism',
    scaleType: 'frequency',
    diagnosticWeight: 1.9,
    symptomType: 'modifier',
    conditionAssociations: ['circadian_disruption', 'metabolic_dysfunction'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'circadian',
    displayOrder: 11,
    requiredLevel: 'standard'
  },
  {
    id: 12,
    category: 'upper_gi',
    subcategory: 'circadian_timing',
    questionText: 'How often do you experience digestive symptoms that vary with seasonal changes?',
    questionContext: 'Digestion worse in winter, better in summer, or changing with daylight patterns',
    clinicalSignificance: 'Indicates light-dependent circadian rhythm disruption affecting digestive hormone cycling',
    scaleType: 'frequency',
    diagnosticWeight: 1.7,
    symptomType: 'modifier',
    conditionAssociations: ['seasonal_affective_disorder', 'circadian_disruption', 'vitamin_d_deficiency'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'circadian',
    displayOrder: 12,
    requiredLevel: 'optional'
  },

  // ====== SMALL INTESTINE HEALTH (15 QUESTIONS) ======
  {
    id: 13,
    category: 'small_intestine',
    subcategory: 'sibo_bacterial_overgrowth',
    questionText: 'How do carbohydrate-rich foods affect your digestive comfort?',
    questionContext: 'Delayed bloating that occurs well after the meal, particularly with starches, sugars, or fiber',
    clinicalSignificance: 'Hallmark sign of SIBO - bacterial fermentation in small intestine creates delayed gas production',
    scaleType: 'frequency',
    diagnosticWeight: 3.0,
    symptomType: 'root_cause',
    conditionAssociations: ['SIBO', 'bacterial_overgrowth', 'carbohydrate_malabsorption'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 13,
    requiredLevel: 'required'
  },
  {
    id: 14,
    category: 'small_intestine',
    subcategory: 'sibo_bacterial_overgrowth',
    questionText: 'How does going without eating for 12+ hours affect your digestive symptoms?',
    questionContext: 'Whether intentional fasting, skipping meals, or longer gaps between eating',
    clinicalSignificance: 'Classic SIBO pattern - removing bacterial fuel (food) reduces fermentation and symptoms',
    scaleType: 'frequency',
    diagnosticWeight: 2.8,
    symptomType: 'root_cause',
    conditionAssociations: ['SIBO', 'bacterial_overgrowth'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 14,
    requiredLevel: 'required'
  },
  {
    id: 15,
    category: 'small_intestine',
    subcategory: 'sibo_bacterial_overgrowth',
    questionText: 'How do fermented foods (kombucha, sauerkraut, yogurt) affect how you feel?',
    questionContext: 'Increased bloating, gas, or digestive discomfort after eating fermented foods',
    clinicalSignificance: 'Indicates histamine intolerance or existing bacterial overgrowth - adding more bacteria worsens symptoms',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    symptomType: 'primary_symptom',
    conditionAssociations: ['SIBO', 'histamine_intolerance', 'bacterial_overgrowth'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 15,
    requiredLevel: 'standard'
  },
  {
    id: 16,
    category: 'small_intestine',
    subcategory: 'food_sensitivity_immune',
    questionText: 'How often do specific foods make you feel tired, brain foggy, or mentally unclear?',
    questionContext: 'Mental/cognitive symptoms within hours of eating certain foods',
    clinicalSignificance: 'Indicates intestinal permeability allowing food proteins to trigger neuroinflammation',
    scaleType: 'frequency',
    diagnosticWeight: 2.7,
    symptomType: 'root_cause',
    conditionAssociations: ['leaky_gut', 'food_sensitivity', 'neuroinflammation'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 16,
    requiredLevel: 'required'
  },
  {
    id: 17,
    category: 'small_intestine',
    subcategory: 'food_sensitivity_immune',
    questionText: 'How often do you experience skin reactions (rashes, eczema, acne) related to food intake?',
    questionContext: 'Skin problems that correlate with eating specific foods or food categories',
    clinicalSignificance: 'Gut-skin axis dysfunction indicating intestinal permeability and systemic inflammation',
    scaleType: 'frequency',
    diagnosticWeight: 2.5,
    symptomType: 'primary_symptom',
    conditionAssociations: ['leaky_gut', 'food_sensitivity', 'systemic_inflammation'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 17,
    requiredLevel: 'standard'
  },
  {
    id: 18,
    category: 'small_intestine',
    subcategory: 'food_sensitivity_immune',
    questionText: 'How often do you crave foods that you suspect don\'t agree with you?',
    questionContext: 'Strong cravings for foods that seem to cause digestive or other symptoms',
    clinicalSignificance: 'Indicates food addiction patterns often associated with leaky gut and opioid-like food reactions',
    scaleType: 'frequency',
    diagnosticWeight: 2.1,
    symptomType: 'secondary_symptom',
    conditionAssociations: ['food_addiction', 'leaky_gut', 'opioid_excess'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 18,
    requiredLevel: 'standard'
  },
  {
    id: 19,
    category: 'small_intestine',
    subcategory: 'intestinal_permeability',
    questionText: 'How often do you experience joint pain or muscle aches that seem food-related?',
    questionContext: 'Joint or muscle pain that increases after eating or correlates with certain foods',
    clinicalSignificance: 'Classic sign of intestinal permeability - food proteins triggering autoimmune-like inflammation',
    scaleType: 'frequency',
    diagnosticWeight: 2.9,
    symptomType: 'root_cause',
    conditionAssociations: ['leaky_gut', 'autoimmune_reactivity', 'systemic_inflammation'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 19,
    requiredLevel: 'required'
  },
  {
    id: 20,
    category: 'small_intestine',
    subcategory: 'intestinal_permeability',
    questionText: 'How often do you have seasonal allergies or environmental sensitivities?',
    questionContext: 'Reactions to pollen, dust, chemicals, or environmental factors',
    clinicalSignificance: 'Indicates compromised immune barrier function - often correlates with intestinal permeability',
    scaleType: 'frequency',
    diagnosticWeight: 2.0,
    symptomType: 'secondary_symptom',
    conditionAssociations: ['leaky_gut', 'immune_dysregulation', 'mast_cell_activation'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 20,
    requiredLevel: 'standard'
  },
  {
    id: 21,
    category: 'small_intestine',
    subcategory: 'intestinal_permeability',
    questionText: 'How often do you experience mood changes (anxiety, depression, irritability) related to eating?',
    questionContext: 'Emotional or mental symptoms that occur within hours of eating',
    clinicalSignificance: 'Gut-brain axis disruption indicating intestinal permeability affecting neurotransmitter production',
    scaleType: 'frequency',
    diagnosticWeight: 2.6,
    symptomType: 'primary_symptom',
    conditionAssociations: ['leaky_gut', 'gut_brain_axis_dysfunction', 'neurotransmitter_imbalance'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 21,
    requiredLevel: 'required'
  },
  {
    id: 22,
    category: 'small_intestine',
    subcategory: 'seed_oil_inflammation',
    questionText: 'How do foods cooked in vegetable oils (canola, soybean, corn oil) affect how you feel?',
    questionContext: 'Restaurant food, fried foods, or home cooking with industrial seed oils. Rate 0 if you avoid these oils.',
    clinicalSignificance: 'Modern insight: Seed oils create intestinal inflammation and disrupt omega-6/3 ratios',
    scaleType: 'frequency',
    diagnosticWeight: 2.3,
    symptomType: 'root_cause',
    conditionAssociations: ['seed_oil_inflammation', 'omega_imbalance', 'intestinal_inflammation'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'processed_foods',
    displayOrder: 22,
    requiredLevel: 'required'
  },
  {
    id: 23,
    category: 'small_intestine',
    subcategory: 'seed_oil_inflammation',
    questionText: 'How do processed foods affect your energy and inflammation levels?',
    questionContext: 'Joint pain, skin issues, or digestive inflammation after packaged/processed foods. Rate 0 if you avoid processed foods.',
    clinicalSignificance: 'Direct inflammatory response to processed food additives and industrial oils',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    symptomType: 'primary_symptom',
    conditionAssociations: ['processed_food_sensitivity', 'systemic_inflammation', 'additive_sensitivity'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'processed_foods',
    displayOrder: 23,
    requiredLevel: 'standard'
  },
  {
    id: 24,
    category: 'small_intestine',
    subcategory: 'seed_oil_inflammation',
    questionText: 'How do foods with artificial preservatives, colors, or flavors affect how you feel?',
    questionContext: 'Foods with ingredients like MSG, artificial colors, BHT, sodium benzoate, etc. Rate 0 if you avoid foods with artificial additives.',
    clinicalSignificance: 'Chemical additives disrupt gut barrier function and trigger immune responses',
    scaleType: 'frequency',
    diagnosticWeight: 1.9,
    symptomType: 'modifier',
    conditionAssociations: ['chemical_sensitivity', 'gut_barrier_dysfunction', 'immune_activation'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'processed_foods',
    displayOrder: 24,
    requiredLevel: 'standard'
  },
  {
    id: 25,
    category: 'small_intestine',
    subcategory: 'malabsorption_advanced',
    questionText: 'How frequently do you experience numbness, tingling, or nerve-related symptoms?',
    questionContext: 'Peripheral neuropathy, pins and needles. 0=Never experience these symptoms, 5=Daily nerve symptoms.',
    clinicalSignificance: 'Indicates B12, B6, or folate malabsorption - serious small intestine dysfunction',
    scaleType: 'frequency',
    diagnosticWeight: 2.8,
    symptomType: 'root_cause',
    conditionAssociations: ['B_vitamin_malabsorption', 'pernicious_anemia', 'small_intestine_damage'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 25,
    requiredLevel: 'standard'
  },
  {
    id: 26,
    category: 'small_intestine',
    subcategory: 'malabsorption_advanced',
    questionText: 'How often do your fingernails chip, peel, crack, or have white spots?',
    questionContext: 'Poor nail quality, ridges, white spots, or easy breaking',
    clinicalSignificance: 'Indicates zinc, protein, and mineral malabsorption affecting collagen synthesis',
    scaleType: 'frequency',
    diagnosticWeight: 2.2,
    symptomType: 'primary_symptom',
    conditionAssociations: ['zinc_deficiency', 'protein_malabsorption', 'mineral_malabsorption'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 26,
    requiredLevel: 'standard'
  },
  {
    id: 27,
    category: 'small_intestine',
    subcategory: 'malabsorption_advanced',
    questionText: 'How often do you experience muscle cramps, especially in legs or feet?',
    questionContext: 'Muscle cramps, charlie horses, or muscle spasms particularly at night',
    clinicalSignificance: 'Indicates magnesium, potassium, or calcium malabsorption - critical mineral deficiencies',
    scaleType: 'frequency',
    diagnosticWeight: 2.5,
    symptomType: 'primary_symptom',
    conditionAssociations: ['magnesium_deficiency', 'electrolyte_imbalance', 'mineral_malabsorption'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 27,
    requiredLevel: 'standard'
  },

  // ====== LARGE INTESTINE FUNCTION (10 QUESTIONS) ======
  {
    id: 28,
    category: 'large_intestine',
    subcategory: 'bowel_movement_patterns',
    questionText: 'How often do you have fewer than one complete bowel movement per day?',
    questionContext: 'Not having at least one substantial bowel movement daily',
    clinicalSignificance: 'Constipation indicates compromised colon function and increased toxin reabsorption',
    scaleType: 'frequency',
    diagnosticWeight: 2.5,
    symptomType: 'root_cause',
    conditionAssociations: ['constipation', 'colon_dysfunction', 'dysbiosis'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 28,
    requiredLevel: 'required'
  },
  {
    id: 29,
    category: 'large_intestine',
    subcategory: 'bowel_movement_patterns',
    questionText: 'How often are your stools not well-formed (too loose, too hard, or irregular shape)?',
    questionContext: 'Bristol stool chart types 1-2 (too hard) or 6-7 (too loose), not type 3-5 (ideal)',
    clinicalSignificance: 'Stool consistency reflects colon transit time, water absorption, and microbiome balance',
    scaleType: 'frequency',
    diagnosticWeight: 2.3,
    symptomType: 'primary_symptom',
    conditionAssociations: ['IBS', 'dysbiosis', 'malabsorption', 'inflammation'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 29,
    requiredLevel: 'required'
  },
  {
    id: 30,
    category: 'large_intestine',
    subcategory: 'bowel_movement_patterns',
    questionText: 'How often do you experience excessive gas with strong odor?',
    questionContext: 'Foul-smelling gas that\'s socially disruptive or unusually strong',
    clinicalSignificance: 'Indicates pathogenic bacterial overgrowth producing sulfur compounds and toxins',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    symptomType: 'primary_symptom',
    conditionAssociations: ['pathogenic_overgrowth', 'sulfur_reducing_bacteria', 'dysbiosis'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 30,
    requiredLevel: 'standard'
  },
  {
    id: 31,
    category: 'large_intestine',
    subcategory: 'microbiome_disruption',
    questionText: 'How has any antibiotic use in the past 2 years affected your digestive health?',
    questionContext: 'Any antibiotic use including oral, topical, or IV antibiotics. Rate 0 if no antibiotic use in past 2 years.',
    clinicalSignificance: 'Antibiotics severely disrupt microbiome diversity and can create long-term dysbiosis',
    scaleType: 'quantity',
    diagnosticWeight: 2.7,
    symptomType: 'root_cause',
    conditionAssociations: ['antibiotic_associated_dysbiosis', 'candida_overgrowth', 'C_diff_risk'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 31,
    requiredLevel: 'required'
  },
  {
    id: 32,
    category: 'large_intestine',
    subcategory: 'microbiome_disruption',
    questionText: 'How often do you experience yeast-related symptoms that worsen with sugar or alcohol?',
    questionContext: 'Yeast infections, thrush, or other fungal issues that flare with sugar intake',
    clinicalSignificance: 'Indicates candida overgrowth often following antibiotic use or high sugar diet',
    scaleType: 'frequency',
    diagnosticWeight: 2.6,
    symptomType: 'root_cause',
    conditionAssociations: ['candida_overgrowth', 'fungal_dysbiosis', 'sugar_sensitivity'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 32,
    requiredLevel: 'standard'
  },
  {
    id: 33,
    category: 'large_intestine',
    subcategory: 'modern_dysbiosis_factors',
    questionText: 'How often do you feel worse in moldy or musty environments?',
    questionContext: 'Symptoms worsen in water-damaged buildings, basements, or moldy areas',
    clinicalSignificance: 'Indicates mold sensitivity often associated with gut dysbiosis and mycotoxin burden',
    scaleType: 'frequency',
    diagnosticWeight: 2.2,
    symptomType: 'modifier',
    conditionAssociations: ['mold_sensitivity', 'mycotoxin_exposure', 'biotoxin_illness'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'mold',
    displayOrder: 33,
    requiredLevel: 'standard'
  },
  {
    id: 34,
    category: 'large_intestine',
    subcategory: 'modern_dysbiosis_factors',
    questionText: 'How do artificial sweeteners or sugar substitutes affect your digestive health?',
    questionContext: 'Aspartame, sucralose, saccharin, acesulfame K, or other artificial sweeteners. Rate 0 if you avoid artificial sweeteners.',
    clinicalSignificance: 'Modern insight: Artificial sweeteners disrupt gut microbiome and glucose metabolism',
    scaleType: 'frequency',
    diagnosticWeight: 2.1,
    symptomType: 'modifier',
    conditionAssociations: ['microbiome_disruption', 'glucose_intolerance', 'dysbiosis'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'processed_foods',
    displayOrder: 34,
    requiredLevel: 'standard'
  },
  {
    id: 35,
    category: 'large_intestine',
    subcategory: 'modern_dysbiosis_factors',
    questionText: 'How often do you experience digestive symptoms that worsen with stress or poor sleep?',
    questionContext: 'Gut symptoms directly correlate with stress levels or sleep quality',
    clinicalSignificance: 'HPA axis and circadian disruption directly affects gut microbiome composition and function',
    scaleType: 'frequency',
    diagnosticWeight: 2.3,
    symptomType: 'modifier',
    conditionAssociations: ['stress_induced_dysbiosis', 'circadian_microbiome_disruption', 'HPA_axis_dysfunction'],
    isTraditional: true,
    isModernInsight: false,
    environmentalFactor: 'stress',
    displayOrder: 35,
    requiredLevel: 'standard'
  },
  {
    id: 36,
    category: 'large_intestine',
    subcategory: 'modern_dysbiosis_factors',
    questionText: 'How often do you consume glyphosate-exposed foods (non-organic grains, legumes)?',
    questionContext: 'Conventional wheat, oats, beans, or other non-organic crops commonly sprayed with glyphosate',
    clinicalSignificance: 'Modern insight: Glyphosate acts as antibiotic, disrupting beneficial gut bacteria',
    scaleType: 'frequency',
    diagnosticWeight: 2.0,
    symptomType: 'modifier',
    conditionAssociations: ['glyphosate_exposure', 'microbiome_disruption', 'leaky_gut'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'chemical_toxins',
    displayOrder: 36,
    requiredLevel: 'optional'
  },
  {
    id: 37,
    category: 'large_intestine',
    subcategory: 'pathogenic_overgrowth',
    questionText: 'How often do you experience anal itching or discomfort?',
    questionContext: 'Itching, burning, or discomfort around the anal area',
    clinicalSignificance: 'Often indicates candida, pinworm, or other pathogenic overgrowth in large intestine',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    symptomType: 'primary_symptom',
    conditionAssociations: ['candida_overgrowth', 'parasites', 'pathogenic_bacteria'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 37,
    requiredLevel: 'standard'
  },

  // ====== LIVER AND DETOXIFICATION (8 QUESTIONS) ======
  {
    id: 38,
    category: 'liver_detox',
    subcategory: 'detoxification_capacity',
    questionText: 'How do chemicals, perfumes, or strong smells affect how you feel?',
    questionContext: 'Reactions to cleaning products, fragrances, etc. 0=No sensitivity/reactions, 5=Always react strongly.',
    clinicalSignificance: 'Indicates impaired Phase I detoxification creating chemical sensitivity and toxin accumulation',
    scaleType: 'frequency',
    diagnosticWeight: 2.8,
    symptomType: 'root_cause',
    conditionAssociations: ['phase1_detox_impairment', 'chemical_sensitivity', 'liver_congestion'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 38,
    requiredLevel: 'required'
  },
  {
    id: 39,
    category: 'liver_detox',
    subcategory: 'detoxification_capacity',
    questionText: 'How often do you experience headaches, fatigue, or nausea with chemical exposure?',
    questionContext: 'Physical symptoms when exposed to cleaning products, new furniture, or chemical environments',
    clinicalSignificance: 'Direct toxic burden symptoms indicating overwhelmed detoxification pathways',
    scaleType: 'frequency',
    diagnosticWeight: 2.6,
    symptomType: 'primary_symptom',
    conditionAssociations: ['toxic_burden', 'detox_pathway_dysfunction', 'chemical_overload'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 39,
    requiredLevel: 'standard'
  },
  {
    id: 40,
    category: 'liver_detox',
    subcategory: 'detoxification_capacity',
    questionText: 'How does alcohol consumption affect how you feel?',
    questionContext: 'Hangover symptoms, nausea, or feeling unwell from minimal alcohol consumption',
    clinicalSignificance: 'Indicates compromised alcohol dehydrogenase function and impaired Phase II detoxification',
    scaleType: 'frequency',
    diagnosticWeight: 2.5,
    symptomType: 'primary_symptom',
    conditionAssociations: ['alcohol_intolerance', 'aldehyde_toxicity', 'phase2_detox_impairment'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 40,
    requiredLevel: 'standard'
  },
  {
    id: 41,
    category: 'liver_detox',
    subcategory: 'bile_production_flow',
    questionText: 'How often do you experience nausea or stomach upset after eating fatty foods?',
    questionContext: 'Nausea, bloating, or discomfort specifically after eating nuts, oils, or fatty meals',
    clinicalSignificance: 'Indicates inadequate bile production or bile flow obstruction affecting fat digestion',
    scaleType: 'frequency',
    diagnosticWeight: 2.7,
    symptomType: 'root_cause',
    conditionAssociations: ['bile_insufficiency', 'gallbladder_dysfunction', 'fat_malabsorption'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 41,
    requiredLevel: 'required'
  },
  {
    id: 42,
    category: 'liver_detox',
    subcategory: 'bile_production_flow',
    questionText: 'How does eating affect any pain between your shoulder blades?',
    questionContext: 'Referred gallbladder pain pattern. 0=No shoulder blade pain, 5=Severe pain especially after eating.',
    clinicalSignificance: 'Classic gallbladder referral pain indicating bile stasis or gallbladder dysfunction',
    scaleType: 'frequency',
    diagnosticWeight: 2.9,
    symptomType: 'root_cause',
    conditionAssociations: ['gallbladder_dysfunction', 'bile_stasis', 'gallstones'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 42,
    requiredLevel: 'standard'
  },
  {
    id: 43,
    category: 'liver_detox',
    subcategory: 'bile_production_flow',
    questionText: 'How would you describe the color and consistency of your stools?',
    questionContext: 'Rate based on typical stool appearance. 0=Normal brown/well-formed, 5=Consistently pale/floating stools.',
    clinicalSignificance: 'Indicates fat malabsorption due to insufficient bile - serious biliary dysfunction',
    scaleType: 'frequency',
    diagnosticWeight: 3.0,
    symptomType: 'root_cause',
    conditionAssociations: ['bile_insufficiency', 'fat_malabsorption', 'biliary_obstruction'],
    isTraditional: true,
    isModernInsight: false,
    displayOrder: 43,
    requiredLevel: 'required'
  },
  {
    id: 44,
    category: 'liver_detox',
    subcategory: 'environmental_toxin_load',
    questionText: 'How often are you exposed to mold, water damage, or musty environments?',
    questionContext: 'Living or working in buildings with water damage, visible mold, or musty odors',
    clinicalSignificance: 'Modern insight: Mycotoxin exposure overwhelms liver detox capacity and creates biotoxin illness',
    scaleType: 'frequency',
    diagnosticWeight: 2.4,
    symptomType: 'modifier',
    conditionAssociations: ['mycotoxin_exposure', 'biotoxin_illness', 'mold_sensitivity'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'mold',
    displayOrder: 44,
    requiredLevel: 'standard'
  },
  {
    id: 45,
    category: 'liver_detox',
    subcategory: 'environmental_toxin_load',
    questionText: 'How often do you live or work in areas with high air pollution, industrial chemicals, or pesticides?',
    questionContext: 'Urban areas, agricultural regions, or industrial zones with chemical exposure',
    clinicalSignificance: 'Environmental toxin burden exceeds liver capacity creating systemic inflammation and dysfunction',
    scaleType: 'frequency',
    diagnosticWeight: 2.2,
    symptomType: 'modifier',
    conditionAssociations: ['environmental_toxicity', 'chemical_burden', 'systemic_inflammation'],
    isTraditional: false,
    isModernInsight: true,
    environmentalFactor: 'chemical_toxins',
    displayOrder: 45,
    requiredLevel: 'optional'
  }
];

export const SCALE_DEFINITIONS = {
  frequency: [
    { value: 0, label: 'Never', description: 'This never happens to me' },
    { value: 1, label: 'Very Rarely', description: 'A few times per year or less' },
    { value: 2, label: 'Rarely', description: 'A few times per month' },
    { value: 3, label: 'Sometimes', description: 'A few times per week' },
    { value: 4, label: 'Often', description: 'Most days' },
    { value: 5, label: 'Very Often', description: 'Daily or almost daily' }
  ],
  severity: [
    { value: 0, label: 'None', description: 'No symptoms' },
    { value: 1, label: 'Very Mild', description: 'Barely noticeable' },
    { value: 2, label: 'Mild', description: 'Noticeable but not bothersome' },
    { value: 3, label: 'Moderate', description: 'Somewhat bothersome' },
    { value: 4, label: 'Severe', description: 'Very bothersome, affects daily life' },
    { value: 5, label: 'Extremely Severe', description: 'Debilitating, major impact on life' }
  ],
  yes_no: [
    { value: 0, label: 'No', description: 'Definitely no' },
    { value: 5, label: 'Yes', description: 'Definitely yes' }
  ],
  quantity: [
    { value: 0, label: 'None', description: 'Zero/None' },
    { value: 1, label: 'Very Little', description: 'Minimal amount' },
    { value: 2, label: 'Small Amount', description: 'Small but noticeable' },
    { value: 3, label: 'Moderate Amount', description: 'Moderate amount' },
    { value: 4, label: 'Large Amount', description: 'Quite a lot' },
    { value: 5, label: 'Excessive Amount', description: 'Extreme amount' }
  ]
};

// I need to continue with the remaining questions to complete the full 45+ question set
// This is Part 1 of the question library - I'll continue with the remaining categories
